### DISCUSSION TITLE
ilogtail 使用otlp插件 配置文件删除之后，插件还继续运行

### DISCUSSION THREAD

**Discussion by yanggelinux** [alibaba/ilogtail#1030] [Help] [answered]
ilogtail 版本1.6.0
配置文件：
```
enable: true
version: v2
inputs:
- Type: service_otlp
  Protocals:
    GRPC:
      Endpoint: 0.0.0.0:4317
    HTTP:
      Endpoint: 0.0.0.0:4318
aggregators:
- Type: aggregator_base
  MaxLogCount: 512
  MaxLogGroupCount: 4
flushers:
- Type: flusher_stdout
  OnlyStdout: true

```
一直往这个插件发送消息，在不重启ilogtail 的情况下，直接把配置文件删除,插件还继续运行，控制台还继续输出数据。
日志报错：
2023-07-26 20:02:45 [ERR] [plugin_manager.go:188] [HoldOn] [config#/root/ilogtail-1.6.0/./user_yaml_config.d/otlp.yaml,]	AlarmType:CONFIG_STOP_TIMEOUT_ALARM	timeout when stop config, goroutine might leak:logstore	:config	config#/root/ilogtail-1.6.0/./user_yaml_config.d/otlp.yaml:

当version 为v2 的时候 不能使用 processor_add_fields 插件，程序报错：

2023-07-26 20:00:10 [ERR] [plugin_export.go:92] [LoadConfig] AlarmType:CONFIG_LOAD_ALARM	load config error, project:	logstore:	config:config#/root/ilogtail-1.6.0/./user_yaml_config.d/otlp.yaml	error:plugin does not implement PorcessorV2. pluginType: processor_add_fields

切换到v1 才可以使用 processor_add_fields 插件
