### DISCUSSION TITLE
[QUESTION]:更新配置后，写入一条日志，agent会重复上传日志

### DISCUSSION THREAD

**Discussion by lironSmilekill** [alibaba/ilogtail#1180] [Help] [answered]
agent版本：1.7.1 Community Edition
flushers: flusher_elasticsearch

重现步骤：
1.随便更新configserver yaml文件
2.写入一条数据 echo "test:xxxx" >> event_2023072019.log
3.在es里看到新增将近1000条记录，此1000条数据为已上传日志

问题：
怀疑agent加载configserver配置后，文件读取位置错误

日志：
[ilogtail.LOG](https://github.com/alibaba/ilogtail/files/12864485/ilogtail.LOG)

**Comment by liangry** [comment]
通过 ConfigServer 进行的配置和修改，配置自动下发到 remote_yaml_config.d 目录，能够稳定复现重复采集日志，在 user_yaml_config.d 目录配置应该是没有这个问题。简化一下使用场景如下

配置：
```
enable: true
inputs:
  - Type: file_log          # 文件输入类型
    LogPath: .              # 文件路径Glob匹配规则
    FilePattern: simple.log # 文件名Glob匹配规则
flushers:
  - Type: flusher_stdout    # 标准输出
    OnlyStdout: true
```

启动 ilogtail，喂一行日志到 simple.log
```
echo '1' >> simple.log
```

此时 ilogtail 能够正常采集到该行日志
```
2023-10-12 03:06:35 {"content":"1","__tag__:__path__":"/ilogtail/output/simple.log","__time__":"1697079992"}
```

通过 ConfigServer 修改一下上面的配置，修改注释中的任意字符，稍等片刻，刚才那一行日志会被重复采集，下面的第二行预期中应该不会出现
```
2023-10-12 03:06:35 {"content":"1","__tag__:__path__":"/ilogtail/output/simple.log","__time__":"1697079992"}
2023-10-12 03:07:06 {"content":"1","__tag__:__path__":"/ilogtail/output/simple.log","__time__":"1697080023"}
```

从 ilogtail.LOG 中可以看出，配置文件更新后，配置版本从 11 升级到 12，触发从 simple.log 的开始位置读取数据，导致重复采集
```
[2023-10-12 03:07:03.603435]	[info]	[212]	/ilogtail/core/reader/LogFileReader.cpp:776		set the starting position for reading, project:	logstore:	config:config#/ilogtail/output/./remote_yaml_config.d/quick-start@12.yaml	log reader queue name:/ilogtail/output/simple.log	file device:149	file inode:14766	file signature:0	start position:0
```

完整日志如下
[ilogtail.LOG](https://github.com/alibaba/ilogtail/files/12876766/ilogtail.LOG)
