### DISCUSSION TITLE
ilogtail c++ json处理插件性能问题

### DISCUSSION THREAD

**Discussion by cyenxchen** [alibaba/ilogtail#1186] [Help]
使用的官方提供的测试工具（https://github.com/EvanLjp/ilogtail-comparison.git）

测试日志内容：
```json
{"GQlATkwTpI":"CsZSGhhHpXeYfxZcGQKlKjIwDqfgKpWuhxUxxCfNqGZdKkPtyIcHCxHBmLqfptpzsmXTLHwOBIDJagJdyuuuOqBKhJfKeGfcDMVd","GuTUnhOkcc":"BaGWCVQpfUMYqzmyaGyeNhNEIEINXjeoPbElzMCbCtFFmjOAeFkEozjNYazWIMkqcWhabdsjdtCpEkgUktvwbfNxRLBGEhfcwBOS","IvowAsNiWh":"pZPZmvWFLVQCEQaVCSIZGfLLhZSrzXblllWKismTnqFuNMhyiBwsMhyCJXyRUnDkJUlgLVZXnjvnRIoHeukJtpVoGkIRne
scUyNj","NyptLvbQhO":"EJyhuGiYwEjFknWXLcVHdWWSURBbewKsMHDvxmhNxkHEymEmdTAGeTbhNLbVYrlPHDDWaEuLxsUrkJNoZtTdFmnrGmJgCiGQvYFf","RDiamRewCz":"gfluAmnwnIMpEmNIYsJCHzebeIyXuPOAMnkUvkcSOLThmsyVvfjAtbaOAMreGIJeKuzMkRJkKeqDXnuYRInQgEtkYvuAEBewFHFW","count":"27982784","dhcoGUtNIr":"KzDvwDdYOyznqApMfnlTQDvzHRyMHXnOqphrZtTPclzhovjFxiornqHhMCVVPvyQZCmERwlXDqSgUtJleAPBtXQmuOW
zjfNHesRo","jxuTDSkiOt":"vXcDIAnYvataZOvDVnRUMEfpLerUrlpZCLRQTZpHdafGtvCTxxiLZuvsaUdKBNJdBtyoNJfwkEauPPaztDhAKiCLNwGYpIBkPCZC","log_time":"2023-10-17T17:00:41.692631516+08:00","sGdSOOkaus":"AhgRhodiYZoGVSnzgtASNzkFDakSJCbztLUPqcmvfzPNZjmZZjGhfbHLsEMqsOvBsMEPlyZCbQLkTzLcktbpmQQUgeMQLFjJVcQw","yccSbtJAMW":"kPowNrJHqeWypnvByfgqDDrskBsgvqVtnUvEgVpseweHUYsVVlJWNnSLka
PdIjGINpeyTqAhQCFrgLNWEerqPvoSloDxNzxGVLiR","zjWKqPpuyB":"LFLavfRbGTczdnclnZYlaEadvCZgprbmEdrmdIXnenXgFgISPpcfVyVeukFMIbycsvmwEBNZnohQnsZHreSoIyuAFXQixUQcLVPc"} 
```

测试配置：
```yaml
enable: true
inputs:
    - Type: file_log
      LogPath: /var/log/medlinker
      FilePattern: access.log
      ContainerFile: true
      ContainerInfo:
        K8sNamespaceRegex: kubeease-observability
        IncludeK8sLabel:
          job-name: nginx-log-demo-0
processors:
    - Type: processor_json
      SourceKey: content
      KeepSource: false
      ExpandDepth: 1
flushers:
    - Type: flusher_statistics
      RateIntervalMs: 1000000
```

每秒产生25K条日志，使用Go Json处理插件的时候CPU六百多m，而使用C++ Json处理插件的时候CPU1000m左右，简单换算下来差距能有接近40%，这个是不是哪里出问题了😅......
