### DISCUSSION TITLE
[QUESTION]metric_system_v2用influxdb协议输出时报错

### DISCUSSION THREAD

**Discussion by Replux** [alibaba/ilogtail#1362] [Help] [answered]
版本：ilogtail 1.7.0
用户配置如下：
```
enable: true
inputs:
  - Type: metric_system_v2
    CPU: true
    Mem: true
flushers:
  - Type: flusher_http
    RemoteURL: "http://ld-xxxx-proxy-tsdb.lindorm.rds.aliyuncs.com:8242/api/v2/write"
    Convert:
      Protocol: influxdb
      Encoding: custom
```

logtail_plugin.LOG报错内容如下：
```
2024-02-18 21:28:56 [ERR] [flusher_http.go:279] [convertAndFlush] [config#/etc/ilogtail//user_yaml_config.d/host.yaml,] AlarmType:FLUSHER_FLUSH_ALARM   http flusher converter log fail, error:unknown field value: NaN     logstore:       config:config#/etc/ilogtail//user_yaml_config.d/host.yaml
2024-02-18 21:28:56 [ERR] [flusher_http.go:258] [runFlushTask] [config#/etc/ilogtail//user_yaml_config.d/host.yaml,]    AlarmType:FLUSHER_FLUSH_ALARM   http flusher failed convert or flush data, data dropped, error:unknown field value: NaN     logstore:       config:config#/etc/ilogtail//user_yaml_config.d/host.yaml
```

当我把用户配置中的flushers. Convert.Protocol改为custom_single，就没问题，改成influxDb就有问题。从错误日志来看，似乎是metric_system_v2的内容不支持转为influxdb协议？
请问有没有什么解决方案🙏
