### DISCUSSION TITLE
2.0版本文本日志输出插件中ExternalK8sLabelTag配置项不生效

### DISCUSSION THREAD

**Discussion by CodeXuQi** [alibaba/ilogtail#1442] [Help]
2.0版本input中文本日志输出插件的ExternalK8sLabelTag配置项不生效，日志输出不能携带pod的标签信息。容器标准输出是可以携带的，这是什么原因？
ilogtail采用的是daemonset部署的，开启了EnableContainerDiscover
![image](https://github.com/alibaba/ilogtail/assets/51477154/47ec02f9-9713-48a9-bb8d-46e4d1fb420e)

**Comment by 1039219879** [comment]
同问

**Comment by Takuka0311** [comment]
> 2.0版本input中文本日志输出插件的ExternalK8sLabelTag配置项不生效，日志输出不能携带pod的标签信息。容器标准输出是可以携带的，这是什么原因？ ilogtail采用的是daemonset部署的，开启了EnableContainerDiscover ![image](https://private-user-images.githubusercontent.com/51477154/320416430-47ec02f9-9713-48a9-bb8d-46e4d1fb420e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4Mzc1ODgsIm5iZiI6MTcxMzgzNzI4OCwicGF0aCI6Ii81MTQ3NzE1NC8zMjA0MTY0MzAtNDdlYzAyZjktOTcxMy00OGE5LWJiOGQtNDZlNGQxZmI0MjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDAxNTQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMjY1YmQ3ZDQ5ZTFmYmJkOGUxZTYzYzAzNGQ2Mjk1MmY5OWI1NWY5MjE4YmRiM2EwOTAzOTg2MmE1ODM0NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v9TzJugRZOq1yHT2_tV49ReYptbjR_mIunNUpJwmI7k)

请问可以提供一份您的配置，以及Pod的yaml吗？

**Comment by Git4Mark** [comment]
同样的问题
input_file插件`ExternalK8SLabelTag`无法添加tag

loongcollector配置如下
```yaml
apiVersion: v1
data:
  nginx_stdout.yaml: |
    enable: true
    inputs:
      - Type: input_file
        FilePaths:
        - /home/cnp/cnp-nginx/logs/*.log
        EnableContainerDiscovery: true
        Multiline:
          StartPattern: '[\d\.:]+.*'
        ExternalK8SLabelTag:
          app.ccc.comstar/instance: service
          app: app
        ExternalEnvTag:
          COMSTAR_APP_DEPLOY_ENV: deploy_env
          COMSTAR_ENV: comstar_env
        ContainerFilters:
          K8sNamespaceRegex: "^(dev)$"
          IncludeK8sLabel:
            app: nginx                # choose containers with this label
    flushers:
      - Type: flusher_stdout
        OnlyStdout: true
        Tags: true
kind: ConfigMap
metadata:
  name: loongcollector-user-cm
  namespace: dev
```

采集模板pod配置如下
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: dev
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app.ccc.comstar/instance: nginx
        app: nginx
    spec:
      containers:
        - image: 'harbor.comstar:8443/cnp/cnp-nginx:1.23.1'
          name: nginx
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
```

loongcollector收集到的日志如下
```txt
2025-02-28T14:51:49.275631429+08:00 2025-02-28 06:51:49 [LogGroup] topic , logstore , logcount 1, tags 
[Key:"__pack_id__" Value:"4C99A88CAF55C6D2-2"  
Key:"__path__" Value:"/home/cnp/cnp-nginx/logs/access.log"  
Key:"_container_ip_" Value:"10.51.30.120"  
Key:"_container_name_" Value:"nginx"  
Key:"_image_name_" Value:"harbor.comstar:8443/cnp/cnp-nginx:1.23.1"  
Key:"_namespace_" Value:"dev"  Key:"_pod_name_" Value:"nginx-868dbf49bc-8vmnr"  
Key:"_pod_uid_" Value:"ad5e68e0-010c-493b-8594-6a761fa51576"  
Key:"_node_name_" Value:"worker02"  
Key:"_node_ip_" Value:"172.19.195.9"  
Key:"__hostname__" Value:"loongcollector-ds-kx7nd" ]
```tag值为空
loongcollector配置如下
```yaml
apiVersion: v1
data:
  nginx_stdout.yaml: |
    enable: true
    inputs:
      - Type: input_file
        FilePaths:
        - /home/cnp/cnp-nginx/logs/*.log
        EnableContainerDiscovery: true
        Multiline:
          StartPattern: '[\d\.:]+.*'
        ExternalK8SLabelTag:
          app.ccc.comstar/instance: service
          app: app
        ExternalEnvTag:
          COMSTAR_APP_DEPLOY_ENV: deploy_env
          COMSTAR_ENV: comstar_env
        ContainerFilters:
          K8sNamespaceRegex: "^(dev)$"
          IncludeK8sLabel:
            app: nginx                # choose containers with this label
    flushers:
      - Type: flusher_stdout
        OnlyStdout: true
        Tags: true
kind: ConfigMap
metadata:
  name: loongcollector-user-cm
  namespace: dev
```

采集模板pod配置如下
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: dev
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app.ccc.comstar/instance: nginx
        app: nginx
    spec:
      containers:
        - image: 'harbor.comstar:8443/cnp/cnp-nginx:1.23.1'
          name: nginx
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
```

loongcollector收集到的日志如下
```txt
2025-02-28T14:51:49.275631429+08:00 2025-02-28 06:51:49 [LogGroup] topic , logstore , logcount 1, tags 
[Key:"__pack_id__" Value:"4C99A88CAF55C6D2-2"  
Key:"__path__" Value:"/home/cnp/cnp-nginx/logs/access.log"  
Key:"_container_ip_" Value:"10.51.30.120"  
Key:"_container_name_" Value:"nginx"  
Key:"_image_name_" Value:"harbor.comstar:8443/cnp/cnp-nginx:1.23.1"  
Key:"_namespace_" Value:"dev"  Key:"_pod_name_" Value:"nginx-868dbf49bc-8vmnr"  
Key:"_pod_uid_" Value:"ad5e68e0-010c-493b-8594-6a761fa51576"  
Key:"_node_name_" Value:"worker02"  
Key:"_node_ip_" Value:"172.19.195.9"  
Key:"__hostname__" Value:"loongcollector-ds-kx7nd" ]
```
