### DISCUSSION TITLE
daemonset启动有办法添加k8s metadata数据吗

### DISCUSSION THREAD

**Discussion by XuHandsome** [alibaba/ilogtail#1464] [Help]
# 先上配置
## ConfigMap:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ilogtail-user-cm
  namespace: logging-system
data:
  javapp.yaml: |
    enable: true
    inputs:
      - Type: file_log
        LogPath: /app/logs/*/
        FilePattern: "*.log"
        ContainerFile: true
        EnableContainerDiscovery: true
        ContainerInfo:
          K8sNamespaceRegex: default
          IncludeK8sLabel:
            type: backend
          ExternalK8sLabelTag:
            app: app
          ExternalEnvTag:
            _node_name_: _node_name_
    flushers:
      - Type: flusher_stdout
        OnlyStdout: true
```

### DaemonSet
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ilogtail-ds
  namespace: logging-system
  labels:
    k8s-app: logtail-ds
spec:
  selector:
    matchLabels:
      k8s-app: logtail-ds
  template:
    metadata:
      labels:
        k8s-app: logtail-ds
    spec:
      tolerations:
        - operator: Exists                    # deploy on all nodes
      containers:
        - name: logtail
          env:
            - name: ALIYUN_LOG_ENV_TAGS       # add log tags from env
              value: _node_name_|_node_ip_
            - name: _node_name_
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: _node_ip_
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: cpu_usage_limit           # iLogtail's self monitor cpu limit
              value: "1"
            - name: mem_usage_limit           # iLogtail's self monitor mem limit
              value: "512"
          image: harbor.ohops.org/middleware/ilogtail:1.8.8
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 400m
              memory: 384Mi
          volumeMounts:
            - mountPath: /var/run                       # for container runtime socket
              name: run
            - mountPath: /logtail_host                  # for log access on the node
              mountPropagation: HostToContainer
              name: root
              readOnly: true
            - mountPath: /usr/local/ilogtail/checkpoint # for checkpoint between container restart
              name: checkpoint
            # - mountPath: /usr/local/ilogtail/config/local # mount config dir
            - mountPath: /usr/local/ilogtail/user_yaml_config.d # mount config dir
              name: user-config
              readOnly: true
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      volumes:
        - hostPath:
            path: /var/run
            type: Directory
          name: run
        - hostPath:
            path: /
            type: Directory
          name: root
        - hostPath:
            path: /etc/ilogtail-ilogtail-ds/checkpoint
            type: DirectoryOrCreate
          name: checkpoint
        - configMap:
            defaultMode: 420
            name: ilogtail-user-cm
          name: user-config
```

# 问题1
首先这套配置`ContainerFile = true`可以监听到其他pod内指定的/app/logs/*/*.log文件，是正常的，但是我应用所在pod并没有配置`_node_name_`、`_node_ip_`、`ALIYUN_LOG_ENV_TAGS`变量，也就意味着我无法通过`inputs.file_log.ContainerInfo.ExternalEnvTag`来获取到我的pod所在节点的一些信息
```yaml
    inputs:
      - Type: file_log
        LogPath: /app/logs/*/
        FilePattern: "*.log"
        ContainerFile: true
        EnableContainerDiscovery: true
        ContainerInfo:
          K8sNamespaceRegex: default
          IncludeK8sLabel:
            type: backend
          ExternalK8sLabelTag:
            app: app
          ExternalEnvTag:
            _node_name_: _node_name_
```

然而我发现，在阿里云上的的SLS对接ACK集群中的日志，竟然有这个`_node_name_`字段，不知道是怎么配置出来的（请原谅敏感信息厚马）：
<img width="1223" alt="image" src="https://github.com/alibaba/ilogtail/assets/21697438/e2626bfb-fe50-4cc0-9215-d5b52f240449">

# 问题2
能否像filebeat的`processors.add_kubernetes_metadata`一样，获取到一些k8s metadata到日志中来，在我们的使用场景中，很多时候需要这些信息来过滤日志
[参考文档](https://www.elastic.co/guide/en/beats/filebeat/current/add-kubernetes-metadata.html)
