### DISCUSSION TITLE
[QUESTION]:ilogtail 如何采集k8s容器的tag 上报到sls

### DISCUSSION THREAD

**Discussion by wenlong139** [alibaba/ilogtail#1490] [Help] [answered]
使用商业版上报k8s容器日志 会有tag
![image](https://github.com/alibaba/ilogtail/assets/33753333/a6f2df19-e20b-4c5e-a326-fe1f2222058e)
问下社区版logtail 采集日志 如何上报容器的tag

**Comment by quzard** [comment]
你的logtail部署在容器里吗

**Comment by wenlong139** [comment]
> 你的logtail部署在容器里吗

是的 ,部署在k8s

**Comment by quzard** [comment]
![image](https://github.com/alibaba/ilogtail/assets/30899719/3898653a-63d5-4186-a7c6-4f11d6bacd51)

我用开源版main编译后，在docker里测试了一下，可以有tag

**Comment by quzard** [comment, marked as answer]
```yaml
enable: true
inputs:
  - Type: input_file
    FilePaths:
      - /logs/*
    EnableContainerDiscovery: true
    ContainerFilters:
      IncludeEnv:
        name: echo
flushers:
  - Type: flusher_sls
    Region: cn-hangzhou
    Endpoint: cn-hangzhou.log.aliyuncs.com
    Project: yitao-hangzhou
    Logstore: test
```
