### DISCUSSION TITLE
processor_filter_regex 配置没生效

### DISCUSSION THREAD

**Discussion by tianhao98** [alibaba/ilogtail#1891] [Help]
ilogtail 配置
```
    enable: true
    inputs:
      - Type: service_docker_stdout
        Stderr: true
        Stdout: true
        K8sNamespaceRegex: "^(sdb)$"
        IncludeK8sLabel: 
          appType: spring
        BeginLineCheckLength: 200
        BeginLineRegex: "^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}.*"
        ExternalK8sLabelTag:
          group: k8s_label_group
    processors:
      - Type: processor_filter_regex
        Exclude:
          content: ".*cipherimpl.*"
    flushers:
      - Type: flusher_kafka_v2
        Brokers: 
          - kafka-elk-kafka-external-bootstrap.kafka.svc:9094
        Topic: spring-logs
```

ilogtail 发送到 kafka 中的消息
![image](https://github.com/user-attachments/assets/0708dede-2122-4d59-a758-8fb8f000b9ef)

问题：
```
    processors:
      - Type: processor_filter_regex
        Exclude:
          content: ".*cipherimpl.*"

这个配置没有给排除掉
```
