### DISCUSSION TITLE
failed to parse config:native processor plugin comes after extended processor plugin

### DISCUSSION THREAD

**Discussion by SaberChX** [alibaba/ilogtail#2055] [Help] [answered]
使用ilogtail 采集信息， processors 处理规则 如下：

processors:
  - Type: processor_json
    SourceKey: content
    KeepSource: true
    ExpandConnector: ""

  - Type: processor_grok
    SourceKey: content
    Match:
      - '%{WORD:alert_type}\|!%{WORD:serialno}\|!%{WORD:rule_id}\|!%{DATA:rule_name}\|!%{NUMBER:write_date}\|!%{DATA:vuln_type}\|!%{IP:sip}\|!%{NUMBER:sport}\|!%{IP:dip}\|!%{NUMBER:dport}\|!%{NUMBER:severity}\|!%{DATA:host}\|!%{DATA:parameter}\|!%{DATA:uri}\|!%{DATA:filename}\|!%{DATA:referer}\|!%{WORD:method}\|!%{DATA:vuln_desc}\|!%{DATA:public_date}\|!%{DATA:vuln_harm}\|!%{DATA:solution}\|!%{NUMBER:confidence}\|!%{WORD:victim_type}\|!%{WORD:attack_flag}\|!%{IP:attacker}\|!%{IP:victim}\|!%{NUMBER:attack_result}\|!%{DATA:kill_chain}\|!%{WORD:code_language}\|!%{DATA:rule_version}\|!%{DATA:xff}\|!%{DATA:vlan_id}\|!%{DATA:vxlan_id}'
    KeepSource: false
    IgnoreParseFailure: true
  - Type: processor_filter_regex_native
    FilterKey:
      - dip
      - dport
    FilterRegex:
      - ^10.51.10.104$
      - ^445$
      
错误如题：这里是说 processor_filter_regex_native 不能放在processor_grok之后处理。
那通过 processor_grok 提取数据字段后，无法通过指定多个字段 来过滤不想要的数据吗（白名单）

看了processor_filter_regex 插件无法满足，多个条件过滤的场景。
"processor_filter_regex processor插件可以实现对日志的过滤。一条日志只有完全匹配Include中的正则表达式，且不匹配Exclude中的正则表达式时才会被采集，否则直接丢弃。"

有没有什么解决的方法？

## 问题2
尝试仅使用 源生插件， 提示错误：failed to parse config:native processor plugins coexist with extended input plugins

```
enable: true
inputs:
  - Type: service_http_server
    Format: "raw"
    Address: "http://127.0.0.1:12345"
processors:
  - Type: processor_parse_json_native
    SourceKey: content
  - Type: processor_filter_regex_native
    FilterKey:
      - dip
    FilterRegex:
      - ^10.51.10.104$
flushers:
  - Type: flusher_stdout
    OnlyStdout: true
```
