### DISCUSSION TITLE
当前两个kafka flusher都没有实现FlusherV2

### DISCUSSION THREAD

**Discussion by xuzhijvn** [alibaba/ilogtail#2098] [Help] [answered]
当前两个kafka flusher都没有实现FlusherV2，请问是还没来得及实现？还是有其他方面的考量故意不实现？

```
enable: true
global:
  StructureType: v2
inputs:
  - Type: service_http_server
    Format: "raw"
    Address: "http://0.0.0.0:12345"
    QueryParams:
      - "QueryKey"
    QueryParamPrefix: "_param_prefix_"
    HeaderParams:
      - "HeaderKey"
    HeaderParamPrefix: "_header_prefix_"
processors:
  - Type: processor_custom
    URL: "https://postman-echo.com/post"

flushers:
  - Type: flusher_kafka_v2
    Brokers:
      - localhost:9092
    Topic: tony_topic
  - Type: flusher_stdout
    OnlyStdout: true
```

2025-02-17 00:27:25 [ERR] [plugin_export.go:164] [LoadPipeline] AlarmType:CONFIG_LOAD_ALARM     load config error, project:     logstore:       config:my_simple/1      error:plugin does not implement FlusherV2. pluginType: flusher_kafka_v2/4
