### DISCUSSION TITLE
flusher_clickhouse插件建表语句错误

### DISCUSSION THREAD

**Discussion by Git4Mark** [alibaba/ilogtail#2112] [Help]
#### 环境信息
+ k8s1.24.4
+ containerd
+ rhel主机

#### 插件配置
```yaml
inputs:
  - Type: input_container_stdio
    IgnoringStderr: true                # only collect stdout
    Multiline:
      StartPattern: '[\d\.:]+.*'
    ExternalK8SLabelTag:
      app.ccc.comstar/instance: service
    ContainerFilters:
      K8sNamespaceRegex: "^(dev)$"
      IncludeK8sLabel:
        app: nginx                # choose containers with this label
processors:
  - Type: processor_regex       # structure log
    SourceKey: content
    Regex: '([\d\.:]+) - (\S+) \[(\S+) \S+\] \"(\S+) (\S+) ([^\\"]+)\" (\d+) (\d+) \"([^\\"]*)\" \"([^\\"]*)\" \"([^\\"]*)\"'
    Keys:
      - remote_addr
      - remote_user
      - time_local
      - method
      - url
      - protocol
      - status
      - body_bytes_sent
      - http_referer
      - http_user_agent
      - http_x_forwarded_for
flushers:
  - Type: flusher_clickhouse
    Addresses:
    - cnp-log-clickhouse:9000
    Authentication:
      PlainText:
        Database: cnp_log
        Username: cnp_log
        Password: "000000"
    Table: cnp-log
```
#### 错误信息
+ loongcollector.LOG
```txt
[2025-02-25 10:53:52.307195]    [error] [11]    /src/core/pipeline/Pipeline.cpp:498             failed to init pipeline:Go pipeline is invalid, see go_plugin.LOG for detail    Go pipeline num:2       Go pipeline content:{
        "aggregators" :
        [
                {
                        "detail" : {},
                        "type" : "aggregator_default/9"
                }
        ],
        "flushers" :
        [
                {
                        "detail" :
                        {
                                "Addresses" :
                                [
                                        "cnp-log-clickhouse:9000"
                                ],
                                "Authentication" :
                                {
                                        "PlainText" :
                                        {
                                                "Database" : "cnp_log",
                                                "Password" : "000000",
                                                "Username" : "cnp_log"
                                        }
                                },
                                "Table" : "cnp-log"
                        },
                        "type" : "flusher_clickhouse/10"
                }
        ],
        "global" :
        {
                "DefaultLogQueueSize" : 10,
                "EnableTimestampNanosecond" : false,
                "UsingOldContentTag" : false
        },
        "processors" :
        [
                {
                        "detail" :
                        {
                                "Keys" :
                                [
                                        "remote_addr",
                                        "remote_user",
                                        "time_local",
                                        "method",
                                        "url",
                                        "protocol",
                                        "status",
                                        "body_bytes_sent",
                                        "http_referer",
                                        "http_user_agent",
                                        "http_x_forwarded_for"
                                ],
                                "Regex" : "([\\d\\.:]+) - (\\S+) \\[(\\S+) \\S+\\] \\\"(\\S+) (\\S+) ([^\\\\\"]+)\\\" (\\d+) (\\d+) \\\"([^\\\\\"]*)\\\" \\\"([^\\\\\"]*)\\\" \\\"([^\\\\\"]*)\\\"",
                                "SourceKey" : "content"
                        },
                        "type" : "processor_regex/8"
                }
        ]
}
        config:nginx_stdout
[2025-02-25 10:53:52.307235]    [warning]       [11]    /src/core/pipeline/PipelineManager.cpp:116              failed to build pipeline for new config:skip current object     config:nginx_stdout
```
+ go_plugin.LOG
```txt
2025-02-25 10:53:52 [ERR] [flusher_clickhouse.go:290] [createNullBufferTable] [nginx_stdout/2]  AlarmType:FLUSHER_INIT_ALARM    sql:CREATE TABLE IF NOT EXISTS `cnp_log`.`ilogtail_cnp-log_buffer` AS `cnp_log`.`ilogtail_cnp-log` ENGINE = Buffer(cnp_log, ilogtail_cnp-log, 16, 10, 100, 10000, 1000000, 10000000, 100000000)   error:code: 47, message: Missing columns: 'log' 'ilogtail_cnp' while processing query: 'ilogtail_cnp - log', required columns: 'ilogtail_cnp' 'log' 'ilogtail_cnp' 'log'  logstore:       config:nginx_stdout
2025-02-25 10:53:52 [ERR] [flusher_clickhouse.go:151] [Init] [nginx_stdout/2]   AlarmType:FLUSHER_INIT_ALARM    init clickhouse flusher error:code: 47, message: Missing columns: 'log' 'ilogtail_cnp' while processing query: 'ilogtail_cnp - log', required columns: 'ilogtail_cnp' 'log' 'ilogtail_cnp' 'log'  logstore:       config:nginx_stdout
2025-02-25 10:53:52 [ERR] [plugin_export.go:152] [LoadPipeline] AlarmType:CONFIG_LOAD_ALARM     load config error, project:     logstore:       config:nginx_stdout/2   error:code: 47, message: Missing columns: 'log' 'ilogtail_cnp' while processing query: 'ilogtail_cnp - log', required columns: 'ilogtail_cnp' 'log' 'ilogtail_cnp' 'log'
```
+ 关键错误SQL
```sql
CREATE TABLE IF NOT EXISTS `cnp_log`.`ilogtail_cnp-log_buffer` AS `cnp_log`.`ilogtail_cnp-log` ENGINE = Buffer(cnp_log,
ilogtail_cnp-log,
16,
10,
100,
10000,
1000000,
10000000,
100000000)
```
