### DISCUSSION TITLE
processor_add_fields 能力升级

### DISCUSSION THREAD

**Discussion by Takuka0311** [alibaba/ilogtail#2134] [Ideas]
`processor_add_fields`是一个简单而常用的插件。支持将固定的k、v添加到LoongCollector输出的数据中。

我们注意到，在社区群和issue中，很多开发者对于该插件的能力有一些需求，例如：

* https://github.com/alibaba/loongcollector/issues/1652
* https://github.com/alibaba/loongcollector/issues/1801
* https://github.com/alibaba/loongcollector/issues/1965

因此，我们新建了这样一个discussion，整理出一些升级点，欢迎社区同学来参与交流，认领开发。此外，还有其他的想法，也欢迎大家在评论区提出，下面列出的功能会不断更新。

- [ ] `processor_add_fields`实现processor_v2接口
- [ ] 支持引用已有字段或Tag，实现类似“Copy”的效果（Copy tag需要先实现processor_v2接口，通过v2接口获取）。例如原本字段中存在`__tag__:__path__`字段，我们想将它copy一份后续继续处理，可以配置类似这样的采集配置：
  ```yaml
  processors:
    - Type: processor_add_fields
      Fields: 
        file_path: ${__tag__:__path__}
      IgnoreIfExist: false
  ```
- [ ] 支持内置函数，例如添加日志uuid等、添加env、k8s元信息等。
- [ ] 实现C++版本的`processor_add_fields_native`插件，获取更高性能。

补充材料：

* `processor_add_fields`插件的[源代码](https://github.com/alibaba/loongcollector/tree/main/plugins/processor/addfields)。
* 插件的开发可以参考文档：[如何开发扩展Processor插件](https://open.observability.cn/project/loongcollector/how-to-write-processor-plugins/#_top)。

有任何问题欢迎在评论区交流
