### DISCUSSION TITLE
[BUG]: 最新版ilogtail镜像采集异常

### DISCUSSION THREAD

**Discussion by oldthreefeng** [alibaba/ilogtail#2139] [Help]
**Describe the bug**
A clear and concise description of what the bug is, ideally within 20 words.

**iLogtail Running Environment**
Please provide the following information:

- ilogtail version:
sls-opensource-registry.cn-shanghai.cr.aliyuncs.com/ilogtail-community-edition/ilogtail:latest
- Yaml configuration:
```
enable: true
inputs:
  - Type: service_docker_stdout
    Stderr: true
    Stdout: true                
    IncludeK8sLabel:
      prometheus-scrape: kong           
processors:
  - Type: processor_regex       
    NoKeyError: true
    SourceKey: content
    Regex: '^(\S+)\s*-\s*(\S*)\s*\[(\d+/\S+/\d+:\d+:\d+:\d+)\s+\S+\]\s*"([^"]*)"\s*"([^"]*)"\s*(\S*)\s*(\S*)\s*"([^"]*)"\s*"([^"]*)"\s*"([^"]*)"\s*"([0-9a-zA-Z.:, -]*)"\s*"([^"]*)"\s*"([^"]*)"\s*"([^"]*)"\s*"([^"]*)"\s*"([^"]*)"\s*"([^"]*)"\s*"([^"]*)"\s*"([^"]*)"\s*"([^"]*)"\s*"(\S*)"\s*"([^"]*)"\s*"([^"]*)"\s*"([^"]*)"\s*"([^"]*)"\s*"([^"]*)"\s*"([^"]*)"\s*"([^"]*)"\s*"([^"]*)"\s*"([^"]*)"\s*"([^"]*)"\s*"([^"]*)"\s*"([^"]*)"\s*"([^"]*)"\s*"([^"]*)"\s*"([^"]*)"\s*"([^"]*)"\s*(\S*).*'
    Keys:
      - remote_addr
      - remote_user
      - time_local
      - http_host
      - request
      - status
      - body_bytes_sent
      - http_referer
      - http_user_agent
      - http_x_channel_id
      - http_x_forwarded_for
      - http_x_forwarded_prefix
      - http_x_access_time
      - http_traceparent
      - http_x_gd_request_origin
      - http_x_gd_traffic_tags
      - http_x_gd_canary_version
      - request_time
      - uri
      - request_method
      - upstream_addr
      - upstream_bytes_received
      - upstream_cache_status
      - upstream_connect_time
      - upstream_http_x_gd_biz_uri
      - upstream_http_x_gd_biz_errcode
      - upstream_cookie_name
      - upstream_header_time
      - upstream_http_name
      - upstream_response_length
      - upstream_response_time
      - http_x_gd_service
      - http_x_gd_service_name
      - http_user_info
      - http_org_info
      - http_gd_user
      - http_x_gd_traffic_platform
      - upstream_status
flushers:
  - Type: flusher_kafka
    Brokers: 
      - 172.16.61.53:9092
      - 172.16.61.55:9092
      - 172.16.61.56:9092
    Topic: gd_stage_kong_access_log
```

配置是一样的 ， 但是最新版本的镜像没有采集，目前没有查到问题点。 提一个issue 记录一下
docker-pullable://sls-opensource-registry.cn-shanghai.cr.aliyuncs.com/ilogtail-community-edition/ilogtail@sha256:995af6ab80630ec2aefb774e04eeaa5791055df6544ecbf41d7be50b814e7ce0 (异常)

 docker-pullable://sls-opensource-registry.cn-shanghai.cr.aliyuncs.com/ilogtail-community-edition/ilogtail@sha256:bb21d57501e3217a51cbe0871f16e7b75ddf4b77048b8511ae1fc9e1d0181d78 （正常）
