### DISCUSSION TITLE
如何根据数据特征动态选择插件参数？

### DISCUSSION THREAD

**Discussion by xuzhijvn** [alibaba/ilogtail#2244] [Help] [answered]
如下一个典型的场景是需要根据数据特征，使用不同的`flusher_http` Auth信息，但是目前所有数据使用`flusher_http`输出时，Auth等其他参数都是提前固定的：

```yaml
enable: true
global:
  StructureType: v2
inputs:
  - Type: service_kafka
    Format: raw
    Version: 2.7.0
    ClientID: ht-51
    Brokers:
      - 192.168.10.100:9092
      - 192.168.10.101:9092
      - 192.168.10.102:9092
    ConsumerGroup: loongcollector-group-1
    Topics:
      - my-trace-topic
    Authentication:
      SASL:
        Username: xxx
        Password: yyy
        SaslMechanism: SCRAM-SHA-512
processors:
  - Type: processor_langfuse
    OtlpFormat: proto
flushers:
  - Type: flusher_stdout
    OnlyStdout: true
  - Type: flusher_http
    RemoteURL: "http://172.0.0.1/api/public/otel/v1/traces"
    Convert:
      Protocol: raw
      Encoding: protobuf
    Concurrency: 10
    QueueCapacity: 4096
    DropEventWhenQueueFull: true
    Authenticator:
      Type: ext_basicauth/user1
extensions:
  - Type: ext_basicauth/user1
    Username: 'pk-lf-xxxxxxxxx'
    Password: 'sk-lf-yyyyyyyyy'
```

两个可能的实现方式是：

1. 定义多个`pipeline`，它们仅`flusher_http`使用不同的Auth参数。缺点是：`inputs`，`processors`阶段数据处理是重复的，系统整体效率低。
2. 支持在一个`pipeline`里面定义重复的插件类型，如上面的：`flusher_http`，通过其他参数唯一标记插件，如：`id`, `name`，不同的插件处理不同的数据。如下两个`flusher_http`分别用于输出key等于 `alibaba`和`zhongnanhai`的数据：
```yaml
enable: true
global:
  StructureType: v2
inputs:
//省略
processors:
//省略
flushers:
  - Type: flusher_http
    Name: xyz
    Filter: 
       GroupMetadataKeys: "alibaba"
    RemoteURL: "http://172.0.0.1/api/public/otel/v1/traces"
    Authenticator:
      Type: ext_basicauth/user1
  - Type: flusher_http
    Name: abc
    Filter: 
       GroupMetadataKeys: "zhongnanhai"
    RemoteURL: "http://172.0.0.1/api/public/otel/v1/traces"
    Authenticator:
      Type: ext_basicauth/user2
extensions:
  - Type: ext_basicauth/user1
    Username: 'pk-lf-xxxxxxxxx'
    Password: 'sk-lf-yyyyyyyyy'
  - Type: ext_basicauth/user2
    Username: 'pk-lf-aaaaaaaaa'
    Password: 'sk-lf-bbbbbbbbb'
```

是否还有其他方式？？？
