### DISCUSSION TITLE
Filebeat、Fluentd/Fluent Bit优秀功能收集，欢迎留言讨论。

### DISCUSSION THREAD

**Discussion by messixukejia** [alibaba/ilogtail#270] [Show and tell]
欢迎来到 iLogtail 的社区！不管您是 Filebeat、Fluentd/Fluentbit 的资深用户，还是 iLogtail 的忠实粉丝，都欢迎参与 iLogtail 社区的共建。

本贴长期收集：

* 希望 iLogtail 从 Filebeat、Fluentd/Fluentbit 中吸收的优秀功能。
* 希望 iLogtail 与 Filebeat、Fluentd/Fluentbit 使用习惯保持一致的地方。

为了我们更好的理解您的意见，建议贴下对应功能的官方文档。

对于热点意见，我们会优先考虑支持。

**Comment by shalousun** [comment]
filebeat上发现一个比较有意思的功能，针对容器环境stdout。允许用户在业务pod上添加annotation，然后filebeat直接发现和采集
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-tomcat-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: springboot-tomcat
      tier: backend
      version: 1.0.0
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-tomcat
        tier: backend
        version: 1.0.0
      annotations:
        prometheus.io/path: '/benchmark/actuator/prometheus'
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
        # Filebeat ship log
        co.elastic.logs/multiline.type: 'pattern'
        co.elastic.logs/multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
        co.elastic.logs/multiline.negate: 'true'
        co.elastic.logs/multiline.match: 'after'
    spec:
      containers:
        - name: springboot-tomcat
          image: registry.cn-shanghai.aliyuncs.com/shalousun/springboot:2.6.6-tomcat
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: [ "SYS_ADMIN" ] # For arthas
          resources:
            requests:
              cpu: 1
              memory: 512Mi
            limits:
              cpu: 1
              memory: 512Mi
          env:
            - name:  JAVA_OPTS
              value: -server -Xmx512m -Xms512m -Djava.awt.headless=true
            - name: MAX_THREADS
              value: '200'
            - name: CONNECTION_TIMEOUT
              value: '20000'
            - name: MAX_CONNECTIONS
              value: '10000'
            - name: APP_VERSION
              value: '1.0'
            - name: PROFILES
              value: 'container'
            - name: LOGGING_PATTERN_CONSOLE
              value: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %level %logger{36}@%method:%line - %msg%n'
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /benchmark/actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 45
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /benchmark/actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
      - name: harbor-key
```
- Filebeat ship log注释下的annotation filebeat官方提供的
