### DISCUSSION TITLE
我无法将日志传给kafka

### DISCUSSION THREAD

**Discussion by marksugar** [alibaba/ilogtail#401] [Help]
当我按照https://zhuanlan.zhihu.com/p/544081167进行 操作，我并未能日志成功传递到kafka
我的环境和说明如下：

k8s: 1.19
kafka:3.2

在deployment中的nginx日志格式为json
```
        log_format log_json '{ "@timestamp": "$time_local", '
          '"remote_addr": "$remote_addr", '
          '"log_time": "$time_iso8601",'
          '"referer": "$http_referer", '
          '"request": "$request", '
          '"status": $status, '
          '"bytes": $body_bytes_sent, '
          '"agent": "$http_user_agent", '
          '"x_forwarded": "$http_x_forwarded_for", '
          '"up_addr": "$upstream_addr",'
          '"up_host": "$upstream_http_host",'
          '"up_resp_time": "$upstream_response_time",'
          '"request_time": "$request_time"'
          ' }';   
```
得到的日志格式如下：
```
{ "@timestamp": "16/Sep/2022:17:24:03 +0800", "remote_addr": "130.130.0.0", "log_time": "2022-09-16T17:24:03+08:00","referer": "-", "request": "GET / HTTP/1.1", "status": 304, "bytes": 0, "agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36", "x_forwarded": "-", "up_addr": "-","up_host": "-","up_resp_time": "-","request_time": "0.000" }
```
ilogtail-user-cm文件如下：
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ilogtail-user-cm
  namespace: ilogtail
data:
  nginx_stdout.yaml: |
    enable: true
    inputs:
      - Type: service_docker_stdout
        Stderr: false
        Stdout: true
        IncludeK8sLabel:
          app: mark
    processors:
      - Type: processor_json
        SourceKey: content
        KeepSource: false
        ExpandDepth: 1
        ExpandConnector: ""
    flushers:
      - Type: flusher_kafka
        Brokers:
          - 172.16.15.136:9092
        Topic: mark-access-log
  nginx_stderr.yaml: |
    enable: true
    inputs:
      - Type: service_docker_stdout
        Stderr: true
        Stdout: false
        K8sNamespaceRegex: "^(default)$"
        K8sPodRegex: "^(mark-.*)$"
        K8sContainerRegex: "mark"
    flushers:
      - Type: flusher_kafka
        Brokers:
          - 172.16.15.136:9092
        Topic: mark-error-log
---
```
我在kafka中可以查看到topics
```
I have no name!@7b1e5f4c972b:/$ kafka-topics.sh --list --bootstrap-server localhost:9092
__consumer_offsets
access-log
error-log
mark-access-log
```
当我请求，并用kafka-console-consumer.sh 查看时，并没有任何数据
```
I have no name!@7b1e5f4c972b:/$ kafka-console-consumer.sh --topic mark-access-log --from-beginning --bootstrap-server localhost:9092
```
logstash也并未消费

请指正问题所在，感激不尽

谢谢
