### DISCUSSION TITLE
新版flusher kafka数据转换和配置问题讨论

### DISCUSSION THREAD

**Discussion by shalousun** [alibaba/ilogtail#454] [Help] [answered]
# 背景

当前ilogtail flusher kafka  新版本的开发和测试基本已经完毕，但是当前flusher配置存在一些分歧点需要大家一起讨论下。讨论确定后做适量优化修改完成最终flusher kafka版本开发。

# ilogtail日志协议了解

ilogtail单条json日志转换协议内容参考：

```
{
	"contents": {
		"class": "org.springframework.web.servlet.DispatcherServlet@initServletBean:547",
		"application": "springboot-docker",
		"level": "INFO",
		"message": "Completed initialization in 9 ms",
		"thread": "http-nio-8080-exec-10",
		"time": "2022-07-20 16:55:05.415"
	},
	"tags": {
        "k8s.namespace.name":"java_app",
		"host.ip": "192.168.6.128",
		"host.name": "master",
		"log.file.path": "/data/test.log"
	},
	"time": 1664435098
}
```

- 从上面的日志可以看出ilogtail标准的日志协议字段为：contents，tags，time
- contents主要是用户的日志内容，等价于ELK上message字段

# topic配置讨论
针对上面写入的这种日志格式，如果想根据`application`名称针对不用的应用推送到不通的`topic`，
则`topic`可以这样配置。
```yaml
Topic: test_%{attribute.application}
```
最后`ilogtail`就自动将日志推送到`test_springboot-docker`这个`topic`中。

`topic`动态表达式规则：
- `%{attribute.fieldname}`。`attribute`代表从`contents`中取指定字段值
- `%{tag.fieldname}`,`tag`表示从`tags`中取指定字段值，例如：`%{tag.k8s.namespace.name}`
- 其它方式暂不支持

配置讨论点：

- 使用`attribute`代表从`contents`中取指定字段值，这里是否需要和协议字段前缀统一？

  配置动态`topic`是否需要变更为`test_%{contents.application}` ，`filebeat`是直接用的原始字段前缀。

- 从`tags`中取字段替换动态topic时，当前使用的`tag`前缀，是否也需要类似`filebeat`的配置一样直接使用原始字段名作为前缀方便记忆。

# 分区hash分发配置讨论

`ilogtail`一共支持三种分区分发方式：
- `random`随机分发, 默认。
- `roundrobin`轮询分发。
- `hash`分发。

`random`和`roundrobin`分发只需要配置`PartitionerType`指定对应的分区分发方式即可。
`hash`分发相对比较特殊，可以指定`HashKeys`，`HashKeys`的中配置的字段名只能是`contents`中的字段属性。

配置用例：
```yaml
enable: true
inputs:
  - Type: file_log
    LogPath: /home/test_log
    FilePattern: "*.log"
flushers:
  - Type: flusher_kafka_v2
    PartitionerType: hash
    HashKeys:
      - application  //contents中的`application`
    Brokers:
      - 192.XX.XX.1:9092
    Topic: KafkaTestTopic
```
- 对HashKeys的配置，ilogtail实现是基于contents中用户的真实日志字段来做hash计算分发。配置时是否需要加前缀保持和前面配置统一？
```
HashKeys:
  - `contents.application` 主要和topic从字段取值统一
```

**欢迎大家积极参与讨论和提出宝贵的优化建议**
