### DISCUSSION TITLE
k8s部署无法正常产生数据问题

### DISCUSSION THREAD

**Discussion by codingdancer** [alibaba/ilogtail#455] [Help] [answered]
使用k8s 部署，
ilogtail.LOG 日志正常
logtail_plugin.LOG 有一个error： must specify topics for plugin service_kafka
麻烦帮忙看看

配置如下：
config map:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ilogtail-user-cm
  namespace: ilogtail
data:
  kafka_kakfa.yaml: |
    enable: true
    inputs:
      - Type: service_kafka
        Version: 2.1.1
        Brokers: 
          - 10.129.168.144:9092
        ConsumerGroup: skyeyeResult
        Topic:
          - risk_qrs_to_dataexchange
        ClientID: ilogtail
    flushers:   
      - Type: flusher_kafka
        Brokers: 
          - 10.129.168.144:9092
        Topic: bmw_bms_collector_rsk
```

deployment 文件：

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ilogtail-dm
  namespace: ilogtail-ns
  labels:
    k8s-app: ilogtail-dm
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: ilogtail-dm
  template:
    metadata:
      labels:
        k8s-app: ilogtail-dm
    spec:
      containers:
        - image: 'sls-opensource-registry.cn-shanghai.cr.aliyuncs.com/ilogtail-community-edition/ilogtail:latest'
          name: ilogtail
          env:
          	- name: ALIYUN_LOG_ENV_TAGS # add log tags from env
        	  value: _node_name_|_node_ip_
            - name: _node_name_
              valueFrom:
          		fieldRef:
                  apiVersion: v1
         		  fieldPath: spec.nodeName
          	- name: mem_usage_limit
              value: "512"
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 400m
              memory: 384Mi
          volumeMounts:
            - mountPath: /var/run # for container runtime socket
              name: run
            - mountPath: /logtail_host # for log access on the node
              mountPropagation: HostToContainer
              name: root
              readOnly: true
            - mountPath: /usr/local/ilogtail/checkpoint # for checkpoint between container restart
              name: checkpoint
            - mountPath: /usr/local/ilogtail/user_yaml_config.d # mount config dir
              name: user-config
              readOnly: true
      volumes:
        - hostPath:
            path: /var/run
            type: Directory
          name: run
        - hostPath:
            path: /
            type: Directory
          name: root
        - hostPath:
            path: /etc/ilogtail-ilogtail-dm/checkpoint
            type: DirectoryOrCreate
          name: checkpoint
        - configMap:
            defaultMode: 420
            name: ilogtail-user-cm
          name: user-config
```
