### DISCUSSION TITLE
配置ALIYUN_LOG_ENV_TAGS 不起作用

### DISCUSSION THREAD

**Discussion by tianhao98** [alibaba/ilogtail#457] [Help] [answered]
配置
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ilogtail-user-cm
  namespace: elk
data:
  harbor_stdout.yaml: |
    enable: true
    inputs:
      - Type: service_docker_stdout
        Stderr: true
        Stdout: true
        IncludeK8sLabel:
          app: harbor
        ALIYUN_LOG_ENV_TAGS: _node_name_|_node_ip_
    flushers:
      - Type: flusher_stdout
        OnlyStdout: true
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ilogtail-ds
  namespace: elk
  labels:
    k8s-app: logtail-ds
spec:
  selector:
    matchLabels:
      k8s-app: logtail-ds
  template:
    metadata:
      labels:
        k8s-app: logtail-ds
    spec:
      # tolerations:
      # - key: node-role.kubernetes.io/master
      #   effect: NoSchedule
      containers:
      - name: logtail
        env:
          - name: ALIYUN_LOG_ENV_TAGS
            value: _node_name_|_node_ip_
          - name: _node_name_
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: "_node_ip_"
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: cpu_usage_limit
            value: "1"
          - name: mem_usage_limit
            value: "512"
        image: >-
          sls-opensource-registry.cn-shanghai.cr.aliyuncs.com/ilogtail-community-edition/ilogtail:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 400m
            memory: 384Mi
        volumeMounts:
          - mountPath: /var/run
            name: run
          - mountPath: /logtail_host
            mountPropagation: HostToContainer
            name: root
            readOnly: true
          - mountPath: /usr/local/ilogtail/checkpoint
            name: checkpoint
          - mountPath: /usr/local/ilogtail/user_yaml_config.d
            name: user-config
            readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      volumes:
        - hostPath:
            path: /var/run
            type: Directory
          name: run
        - hostPath:
            path: /
            type: Directory
          name: root
        - hostPath:
            path: /var/lib/ilogtail-ilogtail-ds/checkpoint
            type: DirectoryOrCreate
          name: checkpoint
        - configMap:
            defaultMode: 420
            name: ilogtail-user-cm
          name: user-config
```

输出：
```
2022-10-12 09:30:41 {"content":"2022/10/12 09:30:41 \u001b[1;44m[D] [server.go:2619] |    10.22.0.173|\u001b[43m 404 \u001b[0m|  55.206487ms|   match|\u001b[44m GET     \u001b[0m /v2/belllabs/cfltest010606.static2/manifests/v5.1.1   r:/v2/*\u001b[0m","_time_":"2022-10-12T09:30:41.218651992Z","_source_":"stdout","_container_name_":"core","_pod_name_":"harbor-harbor-core-cb6c76d58-klx7l","_namespace_":"devops","_pod_uid_":"b52ce451-7e2f-4230-949b-e8e57b7449dd","_container_ip_":"10.33.3.117","_image_name_":"goharbor/harbor-core:v1.8.1","__time__":"1665567041"}
```

问题：

配置ALIYUN_LOG_ENV_TAGS: _node_name_|_node_ip_ 后，采集的日志中并没有 _node_name_|_node_ip_  相关字段
