### DISCUSSION TITLE
logtail 插件 input   service_kafka报错

### DISCUSSION THREAD

**Discussion by codingdancer** [alibaba/ilogtail#459] [Help] [answered]
docker环境下 采集kakfa 数据 ，发现如下问题：
1.topic 配置问题
    应该使用key 为Topics 配置，否则会报找不到topic
2.sarama-cluster 消费问题
具体报错信息
```
D:\software\dockerdesktop\ilogtail\1.1.1>docker logs docker_ilogtail
ilogtail started. pid: 12
register fun v2 0x697dd0 0x699a90 0x699490 0x699ac0
2022/10/13 03:20:43 DEBUG Now using Go's stdlib log package (via loggers/mappers/stdlib).
load log config /usr/local/ilogtail/plugin_logger.xml
panic: non-positive interval for NewTicker

goroutine 210 [running]:
time.NewTicker(0x0, 0x7f5427a69438)
        /go/src/time/tick.go:24 +0x151
github.com/bsm/sarama-cluster.(*Consumer).cmLoop(0xc0002b42d0, 0xc00066f4a0)
        /src/vendor/github.com/bsm/sarama-cluster/consumer.go:452 +0x5c
github.com/bsm/sarama-cluster.(*loopTomb).Go.func1(0xc000145360, 0xc00021af70)
        /src/vendor/github.com/bsm/sarama-cluster/util.go:73 +0x7d
created by github.com/bsm/sarama-cluster.(*loopTomb).Go
        /src/vendor/github.com/bsm/sarama-cluster/util.go:69 +0x68
ilogtail exited unexpectedly
```
 类似 ： https://blog.csdn.net/ecjtusanhu/article/details/106376699

docker 配置如下：
```
enable: true
inputs:
  - Type: service_kafka
    Version: 2.1.1
    Brokers: 
      - 10.71.48.62:9092
    ConsumerGroup: skyeyeResult
    Topics:
      - test
    ClientID: ilogtail
flushers:   
  - Type: flusher_kafka
    Brokers: 
      - 10.71.48.62:9092
    Topic: bmw_bms_collector_rsk
```
