### DISCUSSION TITLE
测试syslog输入源tcp类型报错

### DISCUSSION THREAD

**Discussion by mcy567** [alibaba/ilogtail#486] [Help] [answered]
**版本：**
ilogtail version 1.1.1 Community Edition

**我的配置：**
```
enable: true
inputs:
- Type: service_syslog
  Address: tcp://0.0.0.0:514
  MaxMessageSize: 65536
processors:
- Type: processor_filter_regex
  Exclude:
    "_content_": ".*"
flushers:
- Type: flusher_stdout
  OnlyStdout: false
```

**测试命令：**
logger -n 172.16.238.40 -T -P 514 -f /test/flog.4g.1.log  -S 512

**logtail_plugin.LOG 日志显示：**
2022-10-25 10:46:02 [ERR] [syslog.go:342] [handle] [config#/opt/ilogtail/./user_yaml_config.d/ilogtail.yaml,]	AlarmType:SERVICE_SYSLOG_STREAM_ALARM **quit stream connection because of scan error out of loop:bufio.Scanner: token too long**	

**logtail_plugin.LOG 日志截图：**
![image](https://user-images.githubusercontent.com/22673808/197754407-5902c8fa-2556-42ad-8a96-610237b3436c.png)

上面的配置我改成udp测试就正常，改成tcp就显示token too long，不太清楚这个是什么问题？可以帮忙解答下吗？
