### DISCUSSION TITLE
ilogtail采集容器日志，有办法指定docker.sock的路径吗？

### DISCUSSION THREAD

**Discussion by mcy567** [alibaba/ilogtail#490] [Help] [answered]
如题，我把ilogtail放在了容器里面，因为容器第一个执行命令是/usr/sbin/init，会覆盖/var/run/里面的内容，挂载的docker.sock会被覆盖掉，所以我把宿主机的/var/run/docker.sock挂载到了/docker.sock下，但是我发现ilogtail无法正常采集容器日志了，请问这个问题有解吗？ilogtail读取容器信息应该是用的这个文件吧？我看vector是可以通过配置docker_host指定docker.sock路径的，不知道ilogtail有没有相关功能？

ilogtail配置：
```
enable: true
inputs:
- Type: service_docker_stdout
  Stdout: true
  Stderr: false
  IncludeLable: 
    aliyun.logs.producer: "stdout" 

flushers:
- Type: flusher_stdout
  OnlyStdout: true
```

vector 配置：
```
[sources.in]
  type = "docker_logs"
  docker_host = "/docker.sock"
  include_containers = [ "prodocker" ]

[sinks.out]
  inputs     = ["in"]
  type       = "blackhole"
```
