### DISCUSSION TITLE
ebpf 使用问题汇总

### DISCUSSION THREAD

**Discussion by EvanLjp** [alibaba/ilogtail#515] [Ideas]
ebpf 对于iLogtail 来说还是一个新的feature ，且目前启动也涉及一些要求，目前的文档仍在建设，2022年11月9日会进行ebpf 数据规范和开发的一部分演示，同时欢迎对遇到的问题进行留言，谢谢。

**Comment by guolifu** [comment]
https://github.com/alibaba/ilogtail/discussions/513

**Comment by zhuanshenlikai** [comment]
#509

**Comment by zhuanshenlikai** [comment]
@EvanLjp 作者好，我这边在宿主机上启动了两个后台服务A和B，请求一个接口，A会向B发送请求。这边有个问题，EBPF.Pid能指定多个端口么，我试了下不知道是不是我格式不对，反正没有成功，想问下这边能指定多个pid么？我后来采用的方式是，在user_yaml_config.d下面新建两个yaml，ebpf1.yaml指定的pid是A服务，ebpf2.yaml指定的pid是B服务，然后启动ilogtail。但是最后在logtail_plugin.LOG下面只看到一个role=c的输出，也就是只采集到了客户端的请求，如下：

`2022-11-11 15:05:47 [INF] [flusher_stdout.go:119] [Flush] [config#/root/ilogtail/output/./user_yaml_config.d/ebpf.yaml,]        {"local_info":"{\"_process_cmd_\":\"./main\",\"_process_pid_\":\"3970\",\"_running_mode_\":\"host\"}","interval":"5","req_type":"GET","req_domain":"124.222.208.135:9999","req_resource":"/getMeta","version":"1","resp_status":"-1","resp_code":"200","protocol":"http","type":"l7_req","role":"c","_remote_addr_":"0.0.0.0","_remote_port_":"9999","_local_port_":"0","_local_addr_":"","conn_id":"5013531103317864485","remote_info":"{\"_remote_host_\":\"0.0.0.0\"}","count":"1","latency_ns":"3265975","req_bytes":"159","resp_bytes":"130","tdigest_latency":"xxxxx","__time__":"1668150345"}:`

这边想问的问题是，为什么服务端没有采集到请求数据。我单独只配置一个服务端的yaml，是能采集到role=s的数据的。总结下两个问题：

1. EBPF.Pid能指定多个pid么？
2. 在A->B这种场景下，我设置了两个yaml分别指向A和B这两个服务，为啥只采集到A发出请求的数据？

多谢！

**Comment by zhuanshenlikai** [comment]
@EvanLjp 你好，我这边想采集下某个容器的请求数据，启动容器我增加了label`name=http10`，我的yaml如下
```
enable: true
inputs:
  - Type: observer_ilogtail_network_v1
    Common:
      FlushOutL4Interval: 5
      FlushOutL7Interval: 5
      IncludeContainerLabels:
        name: http10
    EBPF:
      Enabled: true
processors:
  - Type: processor_default
flushers:
  - Type: flusher_stdout
```
我只想采集这个容器的日志，但是在logtail_plugin.LOG下面还采集到了很多其他的日志，这边`IncludeContainerLabels`这个属性是我使用的有问题么，还望帮忙解答下，谢谢！
