### DISCUSSION TITLE
k8s环境部署使用使用动态topic，tags字段下没有一个字段符合要求，不能代表应用唯一

### DISCUSSION THREAD

**Discussion by haozi4263** [alibaba/ilogtail#561] [Help] [answered]
Topic: pod-%{tag.container.name}
需要一个字段能表示这个应用唯一
container.name 如果里面有多个pod就不是唯一了
container.name 如果pod里面有多个container不能唯一

`Topic: pod-%{tag.container.name}

  "tags": {
    "container.image.name": "ccr.ccs.tencentyun.com/cube-studio/ubuntu-gpu:cuda10.1-cudnn7-python3.6",
    "container.ip": "10.42.2.105",
    "container.name": "main",
    "host.ip": "192.168.0.149",
    "host.name": "k8s-cluster01-ai-dev",
    "k8s.namespace.name": "pipeline",
    "k8s.pod.name": "imageai-q4cvg-3359079637",
    "k8s.pod.uid": "54ade9cd-b993-400f-9d99-08ba3ccb24eb"
  },`

上面根据containe.name获取到的main去创建topic不符合要求，因为改pod下面有2个container

动态topic需要通过如 
  label: app=xxx 来创建就比较符合要求

**Comment by shalousun** [comment, marked as answer]
给`service_docker_stdout`插件配置`ExternalK8sLabelTag` ，例如：
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ilogtail-user-cm
  namespace: ilogtail
data:
  java.yaml: |
    enable: true
    inputs:
      - Type: service_docker_stdout
        Stderr: false
        Stdout: true                # only collect stdout
        ExternalK8sLabelTag:
          app: k8s_label_app   # 添加k8s的label app到字段中
    flushers:
      - Type: flusher_stdout
        OnlyStdout: true
      - Type: flusher_kafka_v2
        Brokers:
          - localhost:9092
        Topic: pod-%{content.k8s_label_app}
        FlusherMode: 1
```
配置日志输出到kafka的样例
```
{
	"contents": {
		"_appname": "springboot-docker",
		"_class": "com.benchmark.springboot.controller.LogController",
		"_date": "2022-12-09 22:44:52.495",
		"_level": "ERROR",
		"_msg": "error log",
		"_source_": "stdout",
		"_thread": "http-nio-8080-exec-10",
		"_time_": "2022-12-09T14:44:52.496861202Z",
		"content": "{\"date\":\"2022-12-09 22:44:52.495\",\"appname\":\"springboot-docker\",\"thread\":\"http-nio-8080-exec-10\",\"level\":\"ERROR\",\"class\":\"com.benchmark.springboot.controller.LogController\",\"msg\":\"error log\"}",
		"k8s_label_app": "springboot-tomcat"
	},
	"tags": {
		"container.image.name": "registry.cn-shanghai.aliyuncs.com/shalousun/springboot:2.6.6-tomcat",
		"container.ip": "172.30.166.139",
		"container.name": "springboot-tomcat",
		"host.ip": "192.168.6.130",
		"host.name": "node1",
		"k8s.namespace.name": "default",
		"k8s.node.ip": "192.168.6.130",
		"k8s.node.name": "node1",
		"k8s.pod.name": "springboot-tomcat-deployment-d4977ddc5-krpfs",
		"k8s.pod.uid": "2520325f-c7a3-4772-9014-309f7c8098a6"
	},
	"time": 1670597092
}
```
- `k8s_label_app`被添加到`contents`中
