### DISCUSSION TITLE
k8s 环境 配置文件超过 1000 个，收集 pod 频繁重启

### DISCUSSION THREAD

**Discussion by tianshimoyi** [alibaba/ilogtail#696] [Help]
k8s 环境搭载 ilogtail, configMap 配置为 1000 个，观察到 pod 频繁重启，查看 pod 内存使用确实是超过了 mem_usage_limit = 16G 的设置，但很快就恢复了。看官网说明是超过限制 5 分钟才会触发熔断机制，看监控是不会触发熔断的。
还想问一下，1000 个配置为什么会占用这么大的内存，想知道内存都是用在了哪些方面？
daemonset 配置关键配置如下：
<img width="256" alt="截屏2023-03-08 下午9 27 04" src="https://user-images.githubusercontent.com/68532999/223725161-e8004326-f2b7-4047-a3b0-6d8b0fd79a46.png">
<img width="396" alt="截屏2023-03-08 下午9 27 23" src="https://user-images.githubusercontent.com/68532999/223725218-f398208c-3d36-421c-8251-8acf64e5893a.png">
<img width="1479" alt="截屏2023-03-08 下午9 30 32" src="https://user-images.githubusercontent.com/68532999/223725856-69da8640-c0f8-47be-b2d3-9211fe8c64c6.png">

**Comment by yyuuttaaoo** [comment]
你的ilogtail版本是多少?1000个配置是什么，有样例吗？

**Reply by tianshimoyi** [reply]
@yyuuttaaoo 
版本： main 分支编译
配置：
```yaml
inputs:
- Type: file_log
  LogPath: %s
  FilePattern: "%s"
  ContainerInfo:
    IncludeK8sLabel:
      %s: %s
    ExternalK8sLabelTag:
      xxxxxx: app
      yyyyyy: system
    ExternalEnvTag:
      XXXXX: group
flushers:
- Type: flusher_pulsar
  URL: "xxxxx"
  Convert:
    TagFieldsRename:
      host.name: hostname
  Topic: xxxxxx
  Authentication:
    Token:
      Token: "xxxxxxxx"
  BlockIfQueueFull: true
  MaxPendingMessages: 1000
```
这样的配置 1000 个

步骤
创建 1 个 pod ，启动 1000 个协程，每个协程向对应的文件内写日志，对应配置文件的 1000 个配置
