### DISCUSSION TITLE
怎么配置ILogtail的file_log输入源DelaySkipBytes配置项

### DISCUSSION THREAD

**Discussion by 96loveslife** [alibaba/ilogtail#727] [Help] [answered]
ilogtail版本为1.3.1，采集配置如下
```yaml
enable: true
inputs:
- Type: file_log
  LogPath: /home/user/software
  FilePattern: test1.log
  TailSizeKB: 0
  DelaySkipBytes: 10240000
flushers:
- Type: flusher_stdout
  OnlyStdout: true
```

按照官方文档描述，DelaySkipBytes配置是`当文件采集位置与当前日志产生位置之间的内容大小超过该值时，直接丢弃落后的数据，单位为字节。如果未添加该参数，则默认使用0，表示不丢弃任何数据`，但实际测试时并未生效。

测试步骤如下
1. 启动ilogtail，正常采集日志文件
2. 杀死ilogtail，继续往日志文件中添加数据
3. 启动ilogtail，发现采集的文件位置依然是上一次采集的位置，并没有做丢弃逻辑。日志输出如下

```log
[2023-03-21 09:30:51.696116]	[warning]	[015190]	/src/core/reader/LogFileReader.cpp:1481		read log delay and force set file pos to file size:/home/user/software/test1.log	fall behind bytes:134062153	skip bytes config:10240000	file size:134586564	read pos:524411
```
