### DISCUSSION TITLE
kafka v2 flusher是否可以支持指定kafka消息内容的key

### DISCUSSION THREAD

**Discussion by jingliming** [alibaba/ilogtail#755] [Help] [answered]
目前kafka v2 flusher发送消息只对value进行了处理，没有指定或者处理key的地方
![image](https://user-images.githubusercontent.com/9865050/229097386-677212e1-0861-4470-8d08-81a863f1553f.png)

**Comment by shalousun** [comment, marked as answer]
key是指partitioning key吧，partitioning key是支持的，把ilogtail的消息分发方式改成`hash`

```
enable: true
inputs:
  - Type: file_log
    LogPath: /home/test_log
    FilePattern: "*.log"
flushers:
  - Type: flusher_kafka_v2
    PartitionerType: hash  # hash分发
    HashKeys:  # 指定自己的hashkey
      - content.application  
    Brokers:
      - 192.XX.XX.1:9092
      - 192.XX.XX.2:9092
      - 192.XX.XX.3:9092
    Topic: KafkaTestTopic
```
