### DISCUSSION TITLE
ilogtail采集容器日志输出到elasticsearch es收不到日志

### DISCUSSION THREAD

**Discussion by xiaoyang2008mmm** [alibaba/ilogtail#776] [Help] [answered]
我用ilogtail采集容器日志    输出到elasticsearch es收不到日志  但是输出到flusher_stdout  是可以的
es版本是es8.6.0版本
用其他的客户端(logstash)往es里写入数据 也是可以的 
帮看下是什么问题？

这是我ilogtail的配置
```
enable: true
inputs:
  - Type: service_docker_stdout
    Stdout: true
    Stderr: false
    #IncludeLabel:
      #ELK: "grow"
      #maintainer: "NGINX Docker Maintainers <docker-maint@nginx.com>"
    IncludeEnv:
      NGINX_VERSION: "1.23.4"

flushers:
  - Type: flusher_elasticsearch
    Addresses:
      - 192.168.10.92:9200
    Index: grow
    Authentication:
      PlainText:
        Username: "elastic"
        Password: "elastic"
```

**Comment by joeCarf** [comment]
hello 由于es8的某些安全设置，可能导致ilogtail无法连接 需要手动关闭一下es的https设置，您可以尝试在${elasticsearch}/config/elasticsearch.yml下将相应的参数设置为false
```# Enable security features
xpack.security.enabled: false

**Reply by q121102302** [reply]
那这样不就等于让es裸奔了吗？

**Comment by shalousun** [comment, marked as answer]
es服务端在使用`basic auth`作为认证的情况下`xpack.security.enabled=true`设置为`true`是没有问题的。
只是flusher在配置Addresses时需要带上连接协议的前缀
```
flushers:
  - Type: flusher_elasticsearch
    Addresses:
      - http://192.168.10.92:9200
    Index: grow
    Authentication:
      PlainText:
        Username: "elastic"
        Password: "elastic"
```
对于不带协议的情况下es官方的go client会出现下面类似的错误：
```
 cannot create client: cannot parse url: parse "127.0.0.1:9200": first path segment in URL cannot contain colon
```
官方es go client例子中也是加了前缀的
```
cfg := elasticsearch.Config{
  Addresses: []string{
    "https://localhost:9200",
    "https://localhost:9201",
  },
  Username: "foo",
  Password: "bar",
}
es, err := elasticsearch.NewClient(cfg)
```
