### DISCUSSION TITLE
发送数据到kafka_2.11-0.10.2异常

### DISCUSSION THREAD

**Discussion by wangpeix** [alibaba/ilogtail#786] [Help] [answered]
## 问题描述
ilogtail-1.4.0发送数据到kafka_2.11-0.10.2报如下异常:
```go
flush kafka write data fail, error:kafka: Failed to produce message to topic test_logtail: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
```
网络是通的，且用python脚本发送到同一个集群也是可以的。
怀疑是logtail go kafka client在兼容`kafka_2.11-0.10.2`上有问题。
辛苦帮忙看下，感谢~

## 任务配置
```yaml
enable: true
inputs:
  - Type: file_log
    LogPath: /data1/logs
    FilePattern: "test.log"
flushers:
  - Type: flusher_kafka_v2
    Brokers:
      - x.x.x.x:9092
    Topic: test_logtail
```
