### DISCUSSION TITLE
make dist编译自定义插件异常

### DISCUSSION THREAD

**Discussion by wangpeix** [alibaba/ilogtail#881] [Help]
## 问题描述
插件配置在`plugins.yml`文件中，如下:
```yaml
common:
  ...
  - gomod: "multirow v1.0.0"
     path: "./plugins/processor/split/multirow"
```

make dist编译时报错，异常日志如下:
```shell
#0 296.7 failed to get modules, err: failed to execute go mod tidy, err: exit status 1, output: go: conflicting replacements for multirow@v1.0.0:
#0 296.7 	/data1/software/0529/ilogtail/plugins/processor/split/multirow
#0 296.7 	/src/plugins/processor/split/multirow
```
帮看下，是哪里配置的有问题? 这样的配置下，` make plugin_local`是可以的。
