### DISCUSSION TITLE
我们采用pod 打label 的方式，自动收集日志，然后部分日志收集到了，部分没有收集到

### DISCUSSION THREAD

**Discussion by Steelki** [alibaba/ilogtail#922] [Help] [answered]
配置如下
apiVersion: v1
kind: ConfigMap
metadata:
  name: ilogtail-user-cm
  namespace: ilogtail
data:
  saas_stdout.yaml: |
    enable: true
    inputs:
      - Type: service_docker_stdout
        Stderr: false
        Stdout: true                # only collect stdout
        BeginLineCheckLength: 5000
        MaxLogSize: 5242880
        BeginLineRegex: "\\d+-\\d+-\\d+.*"
        IncludeK8sLabel:
          ilogtail: enable
    processors:
      - Type: processor_split_log_regex
        SplitRegex: ^\d+-\d+-\d+\s+\d+:\d+:\d+.*
        SplitKey: content
        PreserveOthers: true
      - Type: processor_regex
        SourceKey: content
        Regex: '^([\d-]+\s[\d:]+)[\.,]\d+\|([^:|]+):[^\|]+\|([^\|]+)\|([^-]+)\s-\s+([\s\S]+)$'
        Keys:
          - logtime
          - k8s_pod_name
          - level
          - class
          - log
      - Type: processor_filter_regex
        Include:
          level: ".*"
        Exclude:
          log: "0:shape.*"
      - Type: processor_filter_regex
        Include:
          level: ".*"
        Exclude:
          log: "0:Speed.*"
      - Type: processor_filter_regex
        Include:
          level: ".*"
        Exclude:
          log: "0:Size.*"
      - Type: processor_filter_regex
        Include:
          level: ".*"
        Exclude:
          log: "0:PIDX=.*No data available in kafka, sleep 1s.*"
    flushers:
      - Type: flusher_kafka_v2
        Brokers:
          - xx4:9092
          - xx5:9092
          - xx6:9092
        Topic: ack-ai-server-ilogtail
        Convert:
          Encoding: json

**Comment by messixukejia** [comment]
微信群里的信息都补充下吧

**Comment by linrunqi08** [comment]
这个logtail_plugin.LOG可以发一下，这个需要没有采集的pod对应的节点上ilogtail-ds里的日志。
另外看你配置了很多processor_filter_regex，这个可以确认下是否被exclude掉了

**Comment by Steelki** [comment]
我先把filter 先去掉看下效果

**Comment by Steelki** [comment]
去掉了filter 还是不行，我没有看到采集，新的日志如下
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ilogtail-user-cm
  namespace: ilogtail
data:
  saas_stdout.yaml: |
    enable: true
    inputs:
      - Type: service_docker_stdout
        Stderr: false
        Stdout: true                # only collect stdout
        BeginLineCheckLength: 5000
        MaxLogSize: 5242880
        BeginLineRegex: "\\d+-\\d+-\\d+.*"
        IncludeK8sLabel:
          ilogtail: enable
    processors:
      - Type: processor_split_log_regex
        SplitRegex: ^\d+-\d+-\d+\s+\d+:\d+:\d+.*
        SplitKey: content
        PreserveOthers: true
      - Type: processor_regex
        SourceKey: content
        Regex: '^([\d-]+\s[\d:]+)[\.,]\d+\|([^:\|]+):[^:\|]+\|([^\|]+)\|([^-]+)-([\s\S]+)$'
        Keys:
          - logtime
          - k8s_pod_name
          - level
          - class
          - log
    flushers:
      - Type: flusher_kafka_v2
        Brokers:
          - 172.17.243.194:9092
          - 172.17.243.195:9092
          - 172.17.243.196:9092
        Topic: ack-ai-server-ilogtail
        Convert:
          Encoding: json
```
