### DISCUSSION TITLE
Log to metric processor

### DISCUSSION THREAD

**Discussion by linrunqi08** [alibaba/ilogtail#949] [Ideas]
processor_sls_metric

参数名 | 类型 | 是否必填 | 字段说明
-- | -- | -- | --
MetricTimeKey | String | 否 |  默认使用__time__, 取log.time，如果是用户指定的其他字段，确保是合法的、符合格式的纳秒时间戳
MetricLabelKeys | Array | 否 | labels字段的key列表，如果原字段有__labels__字段，该值为追加
MetricValues | Map | 否 |  时序字段名所使用的key -> 时序值使用的key, 时序值取值为double类型或者double类型的字符串
CustomMetricLabels | Map | 否 | 追加的label

原始数据
```
{
	"labelA": "AAA",
	"labelB": "BBB",
	"labelC": "CCC",
	"nameA": "myname",
	"valueA": "1.0"
	"nameB": "myname2",
	"valueB": "2.0"
}
```
处理配置
```
- Type: processor_sls_metric
    MetricTimeKey: __time__
    MetricLabelsKeys:
      - labelA
      - labelB
      - labelC
    MetricValues: 
        nameA: valueA
        nameB: valueB
    CustomMetricLabels:
        labelD: CustomD
```
处理后的数据
```
{
    "__labels__": "labelA#$#AAA|labelB#$#BBB|labelC#$#CCC|labelD#$#CustomD",
    "__name__": "myname",
    "__value__": "1.0",
    "__time_nanos__": "1234567890000000"
}

{
    "__labels__": "labelA#$#AAA|labelB#$#BBB|labelC#$#CCC|labelD#$#CustomD",
    "__name__": "myname2",
    "__value__": "2.0",
    "__time_nanos__": "1234567890000000"
}
```
