### DISCUSSION TITLE
日志轮换场景，往轮换后的旧文件写日志 iLogtail 有时采集有时不采集

### DISCUSSION THREAD

**Discussion by gohonsen** [alibaba/ilogtail#950] [Help] [answered]
有个 Java SpringBoot 项目的日志量比较少，logback 按天轮换，又将 immediateFlush 参数配置了 false ，这样在日志比较少的时候，ing 日志文件一直没内容，轮换后的日志文件才能看到日志，发现 iLogtail 有时采集轮换后的日志，有时没有采集。（immediateFlush 改为 true 实时写，采集正常没问题的）

手工模拟了一下，iLogtail 采集 ing 文件， move ing  文件后继续往move 后的日志文件里写内容，也会出现这样的情况。

iLogtail 采集配置：
```
enable: true
inputs:
  - Type: file_log
    LogPath: /home/tomcat/logs/es
    FilePattern: es*.ing
processors:
  - Type: processor_default
    SourceKey: content
flushers:
  - Type: flusher_stdout
    OnlyStdout: true
```

手工模拟操作的脚本 buff_log.sh：
```
#!/bin/sh

roll_file="es/`date +'%Y-%m-%d-%H-%M-%S'`.log.0"

echo `date +'%Y-%m-%d %H:%M:%S'` "old ing inode `ls -i es/es-log.ing`"
echo `date +'%Y-%m-%d %H:%M:%S'` "mv es/es-log.ing ${roll_file}"
mv es/es-log.ing ${roll_file}
echo `date +'%Y-%m-%d %H:%M:%S'` "old ing rolltate inode `ls -i ${roll_file}`"

echo `date +'%Y-%m-%d %H:%M:%S'` "touch es/es-log.ing"
touch es/es-log.ing
echo `date +'%Y-%m-%d %H:%M:%S'` "new ing inode `ls -i es/es-log.ing`"

echo `date +'%Y-%m-%d %H:%M:%S'` "log to roll file"
echo "`date +'%Y-%m-%d %H:%M:%S'`|183|POST|chc-01|out-router" | stdbuf -oL cat >> ${roll_file}

cat ${roll_file}
```
操作步骤：

1. 创建 ing 日志文件；
2. 配置 iLogtail 采集文件, 启动 iLogtail；
3. 模拟日志轮转 ，模拟多次后发现规律如下：
    
如果直接执行模拟轮换的脚本，move 文件后，往 move 后的文件里面添加内容，iLogtail 没有采集输出； 
 `./buff_log.sh`
    
如果先往日志中生成一条内容，ing 中的立即被采集，再执行模拟轮换的脚本，轮换后新增的日志也会被采集输出；
```
echo "`date +'%Y-%m-%d %H:%M:%S'`|183|POST|chc-01|out-router" | stdbuf -oL cat >> es/es-log.ing
./buff_log.sh
```
    
如果先往日志中生成一条内容，ing 中的被采集后，等待一段时间，再执行模拟轮换的脚本，如果等待的时间不超过180s，iLogtail 会采集输出，否则不再采集 （不是轮换后再等待，轮换后都是脚本立即写入的）；
```
echo "`date +'%Y-%m-%d %H:%M:%S'`|183|POST|chc-01|out-router" | stdbuf -oL cat >> es/es-log.ing && sleep 60 && ./buff_log.sh
echo "`date +'%Y-%m-%d %H:%M:%S'`|183|POST|chc-01|out-router" | stdbuf -oL cat >> es/es-log.ing && sleep 180 &&./buff_log.sh 
echo "`date +'%Y-%m-%d %H:%M:%S'`|183|POST|chc-01|out-router" | stdbuf -oL cat >> es/es-log.ing && sleep 181 && ./buff_log.sh
```
前两条轮换后新增的会采集，最后一条 sleep 181 轮换后新增的不会被采集。
