### DISCUSSION TITLE
Windows下编译运行iLogtail 1.6.0版本出现：被解析的日志里所有字符的前面均有\u0000的问题

### DISCUSSION THREAD

**Discussion by Jiang-Weibo** [alibaba/ilogtail#969] [Help] [answered]
### 问题背景
主机是Windows，从GitHub下载了1.6.0的源代码，并参考[中文用户手册](https://ilogtail.gitbook.io/ilogtail-docs/installation/sources/build)的Windows版本编译部分对源码进行编译。编译成功后，使用`.\ilogtail > stdout.log 2> stderr.log`运行iLogtail，并配置了相关文件，使用官方提供的`processor_split_char processor`插件对`|`分隔符进行解析，在输出文件中出现了“所有字符前均有\u0000”的问题。而在虚拟机（Ubuntu）中直接使用编译好的二进制文件并重复以上操作则没有问题。

### 问题描述
1. 根据手册，编译好后的可执行文件放在output文件夹内，在`user_yaml_config.d`文件夹中创建`file_simple.yaml`配置文件，配置如下
```
#file_simple.yaml配置文件
enable: true
inputs:
  - Type: file_log          # 文件输入类型
    LogPath: .              # 文件路径Glob匹配规则
    FilePattern: simple.log # 文件名Glob匹配规则
processors:
  - Type: processor_split_char
    SourceKey: content
    SplitSep: "|"
    SplitKeys:
      - ip
      - time
      - method
      - url
      - request_time
      - request_length
      - status
      - length
      - ref_url
      - browser
flushers:
  - Type: flusher_stdout    # 标准输出流输出类型
    OnlyStdout: true
```
2. 在后台执行命令`.\ilogtail > stdout.log 2> stderr.log`打开iLogtail
3. 在相同目录下创建`simple.log`日志，并手动添加一条日志如下
`echo "127.0.0.1|10/Aug/2017:14:57:51 +0800|POST|PutData?Category=YunOsAccountOpLog|0.024|18204|200|37|-|aliyun-sdk-java" >> simple.log`
4. 打开文件`stdout.log`发现被分割的后的多个字段的每个字符之间都被添加了`\u0000`，如下
```
2023-07-03 14:45:56 {"__tag__:__path__":".\\simple.log","ip":"\u00001\u00002\u00007\u0000.\u00000\u0000.\u00000\u0000.\u00001\u0000","time":"\u00001\u00000\u0000/\u0000A\u0000u\u0000g\u0000/\u00002\u00000\u00001\u00007\u0000:\u00001\u00004\u0000:\u00005\u00007\u0000:\u00005\u00001\u0000 \u0000+\u00000\u00008\u00000\u00000\u0000","method":"\u0000P\u0000O\u0000S\u0000T\u0000","url":"\u0000P\u0000u\u0000t\u0000D\u0000a\u0000t\u0000a\u0000?\u0000C\u0000a\u0000t\u0000e\u0000g\u0000o\u0000r\u0000y\u0000=\u0000Y\u0000u\u0000n\u0000O\u0000s\u0000A\u0000c\u0000c\u0000o\u0000u\u0000n\u0000t\u0000O\u0000p\u0000L\u0000o\u0000g\u0000","request_time":"\u00000\u0000.\u00000\u00002\u00004\u0000","request_length":"\u00001\u00008\u00002\u00000\u00004\u0000","status":"\u00002\u00000\u00000\u0000","length":"\u00003\u00007\u0000","ref_url":"\u0000-\u0000","browser":"\u0000a\u0000l\u0000i\u0000y\u0000u\u0000n\u0000-\u0000s\u0000d\u0000k\u0000-\u0000j\u0000a\u0000v\u0000a\u0000\r\u0000","__time__":"1688366754"}
```
附上正确解析（忽略换行符）的结果
```
{
    "__tag__:__path__": "/home/test-log/delimiter.log",
    "ip": "127.0.0.1",
    "time": "10/Aug/2017:14:57:51 +0800",
    "method": "POST",
    "url": "PutData?Category=YunOsAccountOpLog",
    "request_time": "0.024",
    "request_length": "18204",
    "status": "200",
    "length": "37",
    "ref_url": "-",
    "browser": "aliyun-sdk-java",
    "__time__": "1657361070"
}
```
