### ISSUE TITLE
[BUG]: ilogtail采集到数据的文件名不正确

### ISSUE THREAD

**Issue by yyuuttaaoo** [alibaba/ilogtail#1102]
**Describe the bug**
29日的文件内容采集后院数据显示都是从27日23点的文件来的
通过checkpoint可以看到，inode复用了，ilogtail把两个文件的文件名搞混了
![image](https://github.com/alibaba/ilogtail/assets/1827594/1a3452c3-f7b5-4409-bd74-09898671b2d1)
![image](https://github.com/alibaba/ilogtail/assets/1827594/ae9146aa-ad23-418c-adcc-d5760afab5f2)

To reproduce
``` shell
touch empty.log
mv empty.log some.log
echo 123 >> some.log 
```

You get
``` plain
2023-08-30 05:51:45 {"content":"123","__path__":"./empty.log","__time__":"1693374703"}
```

**iLogtail Running Environment**
Please provide the following information:

- ilogtail version: 1.7.1
  
- Yaml configuration:

``` yaml
enable: true
inputs:
  - Type: file_log      
    LogPath: .          
    FilePattern: "*.log"
flushers:
  - Type: flusher_stdout
    OnlyStdout: true
```

- ilogtail.LOG:

- logtail_plugin.LOG:
