### ISSUE TITLE
【急】在K8S使用DaemonSet部署，add_fileds下需要添加的字段使用自定义变量

### ISSUE THREAD

**Issue by shangyujia99** [alibaba/ilogtail#1159]
遇到一个新问题，在K8S使用DaemonSet部署，想取自定义容器变量赋值给add_fileds下需要添加的字段，没有效果
```
    processors:
      - Type: processor_add_fields
        Fields:
          __tag__:ll_project: "${ll_project}"
          __tag__:ll_service: "${ll_service}"
        IgnoreIfExist: false
```

_Originally posted by @shangyujia99 in https://github.com/alibaba/ilogtail/discussions/1128#discussioncomment-7108257_

**Comment by linrunqi08** [comment]
你是参考哪里的文档呢？

**Comment by shangyujia99** [comment]
（1）将系统变量采集到日志中完成动态topic绑定
将系统变量采集添加到日志中有两种方式，一种是在ilogtail容器env添加，另一种是通过processor_add_fields 插件添加， 两种方式不同的配置参考下面的介绍
在daemonset或者sidecar方式部署的ilogtail容器env配置部分添加自定义的系统变量，配置参考案例如下：
env:
  - name: ALIYUN_LOG_ENV_TAGS       # add log tags from env
    value: _node_name_|_node_ip_|_app_name_ 
  - name: _app_name_  # 添加自定义_app_name_变量，
    value: kafka
自定义的变量_app_name_被添加到ALIYUN_LOG_ENV_TAGS中，日志的tags中会看到自定义的变量， 此时动态 topic采用%{tag.fieldname}规则配置即可。
使用processor_add_fields 插件系统变量添加到日志中，配置参考如下：
processors:
 - Type: processor_add_fields
   Fields:
     service: ${env_name}
   IgnoreIfExist: false
这里${env_name}生效依赖于ilogtail的enable_env_ref_in_config配置，从ilogtail 1.5.0开始支持。

**Comment by shangyujia99** [comment]
上面是kafkaV2 的文档，将变量加到日志

**Comment by shangyujia99** [comment]
在输入侧使用 ExternalEnvTag参数解决添加字段
```
    inputs:
      - Type: file_log
        LogPath: /opt/logs/
        FilePattern: "*_all.log"
        MaxDepth: 2
        ContainerFile: true
        ContainerInfo:
          IncludeK8sLabel:
            k8s-log-ilogtail: java-log
          ExternalEnvTag:
            ll_project: ll_project
            ll_service: ll_service
```
