### ISSUE TITLE
flusher-clickhouse不刷日志

### ISSUE THREAD

**Issue by starriesWEB** [alibaba/ilogtail#1202]
配置文件
```yaml
flushers:
  - Type: flusher_clickhouse
    Addresses: ["127.0.0.1:9000"]
    Authentication:
      PlainText:
        Database: default
        Username: root
        Password: xxxx
    Table: blade_logs
```
在default数据库会自动生成2个表 `ilogtail_blade_logs`和`ilogtail_blade_logs_buffer`
+ ilogtail_blade_logs 表一直是空的，干什么用的
+ ilogtail_blade_logs_buffer 表的数据会减少，知道是buffer，但是buffer的log刷到哪里去了，是需要自己建一个配置文件中对应的表吗(blade_logs)
