### ISSUE TITLE
[BUG]: 所有 version: v2 的pipeline 无法正常加载

### ISSUE THREAD

**Issue by snakorse** [alibaba/ilogtail#1234]
**Describe the bug**
使用1.8.1版本，未显式配置aggregator的v2版本pipeline启动报错：

> error:plugin does not implement AggregatorV2. pluginType: aggregator_default

**iLogtail Running Environment**
Please provide the following information:

- ilogtail version: v1.8.1
  
- Yaml configuration: 
```
enable: true
version: v2
global:
  AlwaysOnline: true
inputs:
- Type: service_ttlog_starter
flushers:
- Type: flusher_stdout
  OnlyStdout: true
```

- ilogtail.LOG:

- logtail_plugin.LOG:
`2023-11-13 03:33:54 [ERR] [plugin_export.go:116] [LoadConfig] AlarmType:CONFIG_LOAD_ALARM       load config error, project:     logstore:       config:config#/workspaces/ttlogagent/output/./user_yaml_config.d/default.yaml   error:plugin does not implement AggregatorV2. pluginType: aggregator_default`

**Reason**
- 原因是在PR #1169 中，默认的aggregator由`aggregator_base`变成了`aggregator_context`，而插件aggregator_context未实现v2接口
