### ISSUE TITLE
[QUESTION]: flusher_otlp如何传递鉴权信息

### ISSUE THREAD

**Issue by draco1023** [alibaba/ilogtail#1263]
我使用的是windows的1.7.1版本，输出为`flusher_otlp`，尝试了在`Headers`中添加`Authorization: "Basic xxxxxxxxxxxxxxxxxxxx="`，也尝试了直接使用`user`和`password`，确认用户名和密码没错，但是服务端总是返回未授权，在`logtail_plugin.LOG`中有如下日志：

```
AlarmType:FLUSHER_FLUSH_ALARM	send data to otlp server fail, error:rpc error: code = Unauthenticated desc = No valid auth token
```

我的配置大致如下（省略了input）：

```yaml
enable: true
version: v2
flushers:
  - Type: flusher_otlp
    Logs:
      Endpoint: http://192.168.1.111:4317
      Headers:
        Authorization: "Basic xxxxxxxxxxxxxxxxxxxxxxxx"
        organization: default
        stream-name: default
```
