### ISSUE TITLE
[ENHANCEMENT]: flusher 报错不明显

### ISSUE THREAD

**Issue by ltx0633** [alibaba/ilogtail#1273]
**Concisely describe the proposed feature**
>  flusher_elasticsearch 报错不明显

**Describe the solution you'd like (if any)**
>  增加清晰的日志输出

**Additional comments**
当域名不存在的时候，日志中没有明显的错误

```
    flushers:
      - Type: flusher_stdout
        OnlyStdout: true
      - Type: flusher_elasticsearch
        Addresses:
          - "https://test-es.xxx.com"
        Index: log_%{+yyyyMMdd}
        Authentication:
          PlainText:
            Username: elastic
            Password: xxxxx
```
