### ISSUE TITLE
[BUG]:Container startup failed

### ISSUE THREAD

**Issue by clcc2019** [alibaba/ilogtail#1370]
```yaml
ilogtail started. pid: 11
/usr/local/ilogtail/ilogtail_control.sh: line 86:    11 Illegal instruction     (core dumped) ( $bin_file $@ )
ilogtail exited unexpectedly
```

env:
```yaml
System Info:
  Machine ID:                 78daa22aaef34316ab469f39b01c0806
  System UUID:                334eba0a-9934-4764-ba28-409661ffb99f
  Boot ID:                    8d6ec55f-61e2-400e-90c8-d4fb066c8ac1
  Kernel Version:             6.1.0-9-amd64
  OS Image:                   Debian GNU/Linux 12 (bookworm)
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  containerd://1.7.11-k3s2
  Kubelet Version:            v1.29.1+k3s1
  Kube-Proxy Version:         v1.29.1+k3s1
```
