### ISSUE TITLE
ilogtail是否同时支持多个格式的文件

### ISSUE THREAD

**Issue by TaylorJJL** [alibaba/ilogtail#1492]
我尝试一个配置文件里配置多个input插件采集不同格式的文件，但无法正常采集到,，想咨询如何在一个配置中配置多个inpu插件采集不同格式的文件？
写出inputs的配置如下：
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ilogtail-user-cm
  namespace: kube-system
data:
  python-json.yaml: |
    enable: true
    inputs:
      - Type: file_log
        LogPath: "/data/logs/"
        FilePattern: "info.log"
        MaxDepth: 2
    processors:
      - Type: processor_split_log_regex
        SplitRegex: ^\[\s?\S+].*
        SplitKey: content
        PreserveOthers: true
    flushers:
      - Type: flusher_kafka_v2
        Brokers: ...
 enable: true
    inputs:
      - Type: file_log
        LogPath: "/data/logs/"
        FilePattern: "*.json"
        MaxDepth: 2
    processors:
      - Type: processor_json
        SplitKey: content
        KeepSource: false
        ExpandDepth: 1
        ExpandConnector: ""
    flushers:
      - Type: flusher_kafka_v2
        Brokers: 

```
