### ISSUE TITLE
[BUG]: docker根据示例配置文件启动报错

### ISSUE THREAD

**Issue by zijiwork** [alibaba/ilogtail#1888]
**Describe the bug**
A clear and concise description of what the bug is, ideally within 20 words.

**iLogtail Running Environment**
Please provide the following information:

- ilogtail version:
  2.0.4
- Yaml configuration:
```
[root@ZJHZ-SRS-SERVER ilogtail]# cat config/file_simple.yaml
enable: true
inputs:
  - Type: input_file
    FilePaths:
      - /data/apps-logs/*.log
    EnableContainerDiscovery: true
flushers:
  - Type: flusher_stdout
    OnlyStdout: true
[root@ZJHZ-SRS-SERVER ilogtail]# cat config/stdout_simple.yaml
enable: true
inputs:
  - Type: service_docker_stdout # 容器标准输出流输入类型
    Stderr: false               # 不采集标准错误流
    Stdout: true                # 采集标准输出流
flushers:
  - Type: flusher_stdout        # 标准输出流输出类型
    FileName: simple.stdout     # 重定向文件名
```
- ilogtail.LOG:
docker run -d --name docker_ilogtail \
>   -v /:/logtail_host:ro \
>   -v /var/run:/var/run \
>   -v /var/lib/docker_ilogtail/checkpoint:/usr/local/ilogtail/checkpoint \
>   -v `pwd`/config:/usr/local/ilogtail/config/local \
>   sls-opensource-registry.cn-shanghai.cr.aliyuncs.com/ilogtail-community-edition/ilogtail:latest
515a2a6cd76b8c4b0231e51eb4676318fc1c85c393fba8d5389ea2ee8619c9a2

[root@ZJHZ-SRS-SERVER ilogtail]# docker logs -f docker_ilogtail
ilogtail started. pid: 11
/usr/local/ilogtail/ilogtail_control.sh: line 86:    11 Illegal instruction     (core dumped) ( $bin_file $@ )
ilogtail exited unexpectedly

- logtail_plugin.LOG:
