### ISSUE TITLE
[FEATURE]: Windows Support for iLogtail

### ISSUE THREAD

**Issue by yyuuttaaoo** [alibaba/ilogtail#327]
**Concisely describe the proposed feature**
Compile and run ilogtail on Windows.

**Describe the solution you'd like (if any)**
- Fix windows compilation problems.

- Make sure unittest pass on Windows.

- Make sure ilogtail.exe works.

- Add build solution for windows.

- Add windows-build check in GitHub workflow.
  in https://github.com/alibaba/ilogtail/blob/main/.github/workflows/build.yaml
  Add a section 
  ```yaml
        - name: Build core on Windows
          if: matrix.runner == 'windows-2019'
          ......
  ```
