### ISSUE TITLE
[FEATURE]: processor_rename 增加一个保留原字段的选项

### ISSUE THREAD

**Issue by CyshallChan** [alibaba/ilogtail#740]
**Concisely describe the proposed feature**
processor_rename 增加一个保留原字段的选项

**Describe the solution you'd like (if any)**
A clear and concise description of what you want to achieve and implement. For example,
> We can use the package `github.com/gosnmp/gosnmp` to act as an snmp server in a gesture to collect client logs.

**Additional comments**
如下：
```yaml
enable: true
inputs:
  - Type: file_log
    LogPath: /home/test-log/
    FilePattern: key_value.log
processors:
  - Type: processor_rename
    KeepSource: true
    SourceKeys: 
      - key1
    DestKeys:
      - new_key1
flushers:
  - Type: flusher_stdout
    OnlyStdout: true
```
输出：
```shell
{
    "__tag__:__path__": "/home/test_log/key_value.log",
    "key1": "123456",
    "new_key1": "123456",
    "key2": "abcd",
    "__time__": "1657354602"
}
```
如果可以的话，我这边可以提个PR。
