### ISSUE TITLE
[FEATURE]: Support for multiple input configurations

### ISSUE THREAD

**Issue by shalousun** [alibaba/ilogtail#805]
**Concisely describe the proposed feature**
Ability to configure multiple log collection inputs in one yaml configuration file
可以在一个yaml配置文件中配置多个input

For example
```
enable: true
inputs:
   - Type: file_log
      LogPath: /data/logs/StarRocks
      FilePattern: '*.log'
   - Type: file_log
      LogPath: /data/starrocks/
      FilePattern: '*.INFO'
flushers:
   - Type: flusher_stdout
      OnlyStdout: true
```

**Describe the solution you'd like (if any)**

**Additional comments**
For example, the ideal input and output logs.
> The logs are supposed to have the following contents, e.g.,
>
> ``` json
> {"_target_":"127.0.0.1","_field_":"DISMAN-EXPRESSION-MIB::sysUpTimeInstance","_oid_":".1.3.6.1.2.1.1.3.0","_type_":"TimeTicks","_content_":"10423593"}
> ```
