### ISSUE TITLE
[QUESTION]: ilogtail 使用官方提供的镜像无法正常启动以及在以sidecar方式运行时存在日志丢失的情况

### ISSUE THREAD

**Issue by shadowofmoo** [alibaba/ilogtail#853]
测试使用的配置：
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ilogtail-log
  labels:
    app: ilogtail-log
  namespace: test
spec:
  selector:
    matchLabels:
      app: ilogtail-log
  replicas: 1
  template:
    metadata:
      labels:
        app: ilogtail-log
    spec:
      containers:
        - name: log-generate
          image: loggenerate:0.0.2
          volumeMounts:
            - mountPath: /app/logs/
              name: log-file
        - name: ilogtail
          image: ilogtail-custom:0.0.1
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Asia/Shanghai
          volumeMounts:
            - mountPath: /app/user_yaml_config.d/
              name: user-config
              readOnly: true
            - mountPath: /logs/
              name: log-file
      nodeSelector:
        kubernetes.io/hostname: k8s-worker-03
      volumes:
        - name: user-config
          configMap:
            defaultMode: 420
            name: ilogtail-conf
        - name: log-file
          emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ilogtail-conf
  namespace: test
data:
  file_simple.yaml: |
    enable: true
    inputs:
      - Type: file_log
        LogPath: /logs
        FilePattern: "*.log"
    flushers:
      - Type: flusher_kafka_v2
        Brokers:
         - test:9200
        Topic: test

```
问题一，当使用官方的镜像的时候就直接无法启动，报错如下，而使用自制镜像则没有问题
![image](https://github.com/alibaba/ilogtail/assets/124780081/601c1891-dc36-4682-9cf1-c7c9164623fd)

问题二，运行时删除pod，日志总共有3800条日志
![image](https://github.com/alibaba/ilogtail/assets/124780081/59333c03-d8ce-43ea-8159-99e7f3ac966b)

但实际上kafka只接收到了800条日志
![image](https://github.com/alibaba/ilogtail/assets/124780081/bd5d2a1c-1e2a-4acd-b1fd-739a5382e534)
